// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package authlete

// Generated from OpenAPI doc version 3.0.16 and generator version 2.869.25

import (
	"context"
	"fmt"
	"github.com/authlete/authlete-go-sdk/internal/config"
	"github.com/authlete/authlete-go-sdk/internal/hooks"
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
	"github.com/authlete/authlete-go-sdk/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// 🇺🇸 US Cluster
	"https://us.authlete.com",
	// 🇯🇵 Japan Cluster
	"https://jp.authlete.com",
	// 🇪🇺 Europe Cluster
	"https://eu.authlete.com",
	// 🇧🇷 Brazil Cluster
	"https://br.authlete.com",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// Authlete API: Welcome to the **Authlete API documentation**. Authlete is an **API-first service** where every aspect of the
// platform is configurable via API. This documentation will help you authenticate and integrate with Authlete to
// build powerful OAuth 2.0 and OpenID Connect servers.
//
// At a high level, the Authlete API is grouped into two categories:
//
// - **Management APIs**: Enable you to manage services and clients.
// - **Runtime APIs**: Allow you to build your own Authorization Servers or Verifiable Credential (VC) issuers.
//
// ## 🌐 API Servers
//
// Authlete is a global service with clusters available in multiple regions across the world:
//
// - 🇺🇸 **US**: `https://us.authlete.com`
// - 🇯🇵 **Japan**: `https://jp.authlete.com`
// - 🇪🇺 **Europe**: `https://eu.authlete.com`
// - 🇧🇷 **Brazil**: `https://br.authlete.com`
//
// Our customers can host their data in the region that best meets their requirements.
//
// ## 🔑 Authentication
//
// All API endpoints are secured using **Bearer token authentication**. You must include an access token in every request:
//
// ```
// Authorization: Bearer YOUR_ACCESS_TOKEN
// ```
//
// ### Getting Your Access Token
//
// Authlete supports two types of access tokens:
//
// **Service Access Token** - Scoped to a single service (authorization server instance)
//
// 1. Log in to [Authlete Console](https://console.authlete.com)
// 2. Navigate to your service → **Settings** → **Access Tokens**
// 3. Click **Create Token** and select permissions (e.g., `service.read`, `client.write`)
// 4. Copy the generated token
//
// **Organization Token** - Scoped to your entire organization
//
// 1. Log in to [Authlete Console](https://console.authlete.com)
// 2. Navigate to **Organization Settings** → **Access Tokens**
// 3. Click **Create Token** and select org-level permissions
// 4. Copy the generated token
//
// > ⚠️ **Important Note**: Tokens inherit the permissions of the account that creates them. Service tokens can only
// > access their specific service, while organization tokens can access all services within your org.
//
// ### Token Security Best Practices
//
// - **Never commit tokens to version control** - Store in environment variables or secure secret managers
// - **Rotate regularly** - Generate new tokens periodically and revoke old ones
// - **Scope appropriately** - Request only the permissions your application needs
// - **Revoke unused tokens** - Delete tokens you're no longer using from the console
//
// ### Quick Test
//
// Verify your token works with a simple API call:
//
// ```bash
//
//	curl -X GET https://us.authlete.com/api/service/get/list \
//	  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
//
// ```
//
// ## 🎓 Tutorials
//
// If you're new to Authlete or want to see sample implementations, these resources will help you get started:
//
// - [Getting Started with Authlete](https://www.authlete.com/developers/getting_started/)
// - [From Sign-Up to the First API Request](https://www.authlete.com/developers/tutorial/signup/)
//
// ## 🛠 Contact Us
//
// If you have any questions or need assistance, our team is here to help:
//
// - [Contact Page](https://www.authlete.com/contact/)
type Authlete struct {
	SDKVersion           string
	Service              *Service
	Client               *Client
	ClientManagement     *ClientManagement2
	ClientAuthorizations *ClientAuthorizations
	Clients              *Clients
	// Process Device Authorization Request
	// This API parses request parameters of a [device authorization request](https://datatracker.ietf.org/doc/html/rfc8628#section-3.1)
	// and returns necessary data for the authorization server implementation to process the device authorization
	// request further.
	//
	Authorization             *Authorization
	PushedAuthorization       *PushedAuthorization
	Token                     *Token
	Introspection             *Introspection
	Revocation                *Revocation
	Userinfo                  *Userinfo
	GrantManagement           *GrantManagement
	Jwks                      *Jwks
	DynamicClientRegistration *DynamicClientRegistration
	Ciba                      *Ciba
	DeviceFlow                *DeviceFlow
	Jose                      *Jose
	Federation                *Federation
	HardwareSecurityKeys      *HardwareSecurityKeys
	VerifiableCredentials     *VerifiableCredentials
	Lifecycle                 *Lifecycle
	NativeSso                 *NativeSso

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Authlete)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *Authlete) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *Authlete) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *Authlete) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Authlete) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(bearer string) SDKOption {
	return func(sdk *Authlete) {
		security := components.Security{Bearer: &bearer}
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(&security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *Authlete) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Authlete) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Authlete) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *Authlete {
	sdk := &Authlete{
		SDKVersion: "0.0.14",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.0.14 2.869.25 3.0.16 github.com/authlete/authlete-go-sdk",
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	if sdk.sdkConfiguration.Security == nil {
		var envVarSecurity components.Security
		if utils.PopulateSecurityFromEnv(&envVarSecurity) {
			sdk.sdkConfiguration.Security = utils.AsSecuritySource(envVarSecurity)
		}
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Service = newService(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Client = newClient(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.ClientManagement = newClientManagement2(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.ClientAuthorizations = newClientAuthorizations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Clients = newClients(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Authorization = newAuthorization(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PushedAuthorization = newPushedAuthorization(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Token = newToken(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Introspection = newIntrospection(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Revocation = newRevocation(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Userinfo = newUserinfo(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.GrantManagement = newGrantManagement(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Jwks = newJwks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.DynamicClientRegistration = newDynamicClientRegistration(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Ciba = newCiba(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.DeviceFlow = newDeviceFlow(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Jose = newJose(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Federation = newFederation(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.HardwareSecurityKeys = newHardwareSecurityKeys(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.VerifiableCredentials = newVerifiableCredentials(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Lifecycle = newLifecycle(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.NativeSso = newNativeSso(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
