// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package authlete

import (
	"github.com/authlete/authlete-go-sdk/internal/config"
	"github.com/authlete/authlete-go-sdk/internal/hooks"
)

type Clients struct {
	Tokens            *Tokens
	GrantedScopes     *GrantedScopes
	RequestableScopes *RequestableScopes

	rootSDK          *Authlete
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newClients(rootSDK *Authlete, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Clients {
	return &Clients{
		rootSDK:           rootSDK,
		sdkConfiguration:  sdkConfig,
		hooks:             hooks,
		Tokens:            newTokens(rootSDK, sdkConfig, hooks),
		GrantedScopes:     newGrantedScopes(rootSDK, sdkConfig, hooks),
		RequestableScopes: newRequestableScopes(rootSDK, sdkConfig, hooks),
	}
}
