// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthTokenDeleteAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// The identifier of an existing access token. The identifier is the value of the access token
	// or the value of the hash of the access token.
	//
	AccessTokenIdentifier string `pathParam:"style=simple,explode=false,name=accessTokenIdentifier"`
}

func (a *AuthTokenDeleteAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthTokenDeleteAPIRequest) GetAccessTokenIdentifier() string {
	if a == nil {
		return ""
	}
	return a.AccessTokenIdentifier
}

type AuthTokenDeleteAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (a *AuthTokenDeleteAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}
