// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthAuthorizationFailAPIRequest struct {
	// A service ID.
	ServiceID string                              `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.AuthorizationFailRequest `request:"mediaType=application/json"`
}

func (a *AuthAuthorizationFailAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthAuthorizationFailAPIRequest) GetBody() components.AuthorizationFailRequest {
	if a == nil {
		return components.AuthorizationFailRequest{}
	}
	return a.Body
}

type AuthAuthorizationFailAPIResponse struct {
	HTTPMeta                  components.HTTPMetadata `json:"-"`
	AuthorizationFailResponse *components.AuthorizationFailResponse
}

func (a AuthAuthorizationFailAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthAuthorizationFailAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthAuthorizationFailAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthAuthorizationFailAPIResponse) GetAuthorizationFailResponse() *components.AuthorizationFailResponse {
	if a == nil {
		return nil
	}
	return a.AuthorizationFailResponse
}
