// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthAuthorizationAPIRequest struct {
	// A service ID.
	ServiceID string                          `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.AuthorizationRequest `request:"mediaType=application/json"`
}

func (a *AuthAuthorizationAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthAuthorizationAPIRequest) GetBody() components.AuthorizationRequest {
	if a == nil {
		return components.AuthorizationRequest{}
	}
	return a.Body
}

type AuthAuthorizationAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Authorization request processed successfully
	AuthorizationResponse *components.AuthorizationResponse
}

func (a AuthAuthorizationAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthAuthorizationAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthAuthorizationAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthAuthorizationAPIResponse) GetAuthorizationResponse() *components.AuthorizationResponse {
	if a == nil {
		return nil
	}
	return a.AuthorizationResponse
}
