// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthTokenRevokeAPIRequest struct {
	// A service ID.
	ServiceID string                        `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.TokenRevokeRequest `request:"mediaType=application/json"`
}

func (a *AuthTokenRevokeAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthTokenRevokeAPIRequest) GetBody() components.TokenRevokeRequest {
	if a == nil {
		return components.TokenRevokeRequest{}
	}
	return a.Body
}

type AuthTokenRevokeAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Token revoked successfully
	TokenRevokeResponse *components.TokenRevokeResponse
}

func (a AuthTokenRevokeAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthTokenRevokeAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthTokenRevokeAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthTokenRevokeAPIResponse) GetTokenRevokeResponse() *components.TokenRevokeResponse {
	if a == nil {
		return nil
	}
	return a.TokenRevokeResponse
}
