// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthTokenIssueAPIRequest struct {
	// A service ID.
	ServiceID string                       `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.TokenIssueRequest `request:"mediaType=application/json"`
}

func (a *AuthTokenIssueAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthTokenIssueAPIRequest) GetBody() components.TokenIssueRequest {
	if a == nil {
		return components.TokenIssueRequest{}
	}
	return a.Body
}

type AuthTokenIssueAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Token issued successfully
	TokenIssueResponse *components.TokenIssueResponse
}

func (a AuthTokenIssueAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthTokenIssueAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthTokenIssueAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthTokenIssueAPIResponse) GetTokenIssueResponse() *components.TokenIssueResponse {
	if a == nil {
		return nil
	}
	return a.TokenIssueResponse
}
