// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthTokenFailAPIRequest struct {
	// A service ID.
	ServiceID string                      `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.TokenFailRequest `request:"mediaType=application/json"`
}

func (a *AuthTokenFailAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthTokenFailAPIRequest) GetBody() components.TokenFailRequest {
	if a == nil {
		return components.TokenFailRequest{}
	}
	return a.Body
}

type AuthTokenFailAPIResponse struct {
	HTTPMeta          components.HTTPMetadata `json:"-"`
	TokenFailResponse *components.TokenFailResponse
}

func (a AuthTokenFailAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthTokenFailAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthTokenFailAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthTokenFailAPIResponse) GetTokenFailResponse() *components.TokenFailResponse {
	if a == nil {
		return nil
	}
	return a.TokenFailResponse
}
