// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthTokenAPIRequest struct {
	// A service ID.
	ServiceID string                  `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.TokenRequest `request:"mediaType=application/json"`
}

func (a *AuthTokenAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthTokenAPIRequest) GetBody() components.TokenRequest {
	if a == nil {
		return components.TokenRequest{}
	}
	return a.Body
}

type AuthTokenAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Token operation completed successfully
	TokenResponse *components.TokenResponse
}

func (a AuthTokenAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthTokenAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthTokenAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthTokenAPIResponse) GetTokenResponse() *components.TokenResponse {
	if a == nil {
		return nil
	}
	return a.TokenResponse
}
