// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthTokenGetListAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// Client Identifier (client ID or client ID alias).
	//
	ClientIdentifier *string `queryParam:"style=form,explode=true,name=clientIdentifier"`
	// Unique user ID.
	//
	Subject *string `queryParam:"style=form,explode=true,name=subject"`
	// Start index of search results (inclusive). The default value is 0.
	Start *int `queryParam:"style=form,explode=true,name=start"`
	// End index of search results (exclusive). The default value is 5.
	//
	End *int `queryParam:"style=form,explode=true,name=end"`
}

func (a *AuthTokenGetListAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthTokenGetListAPIRequest) GetClientIdentifier() *string {
	if a == nil {
		return nil
	}
	return a.ClientIdentifier
}

func (a *AuthTokenGetListAPIRequest) GetSubject() *string {
	if a == nil {
		return nil
	}
	return a.Subject
}

func (a *AuthTokenGetListAPIRequest) GetStart() *int {
	if a == nil {
		return nil
	}
	return a.Start
}

func (a *AuthTokenGetListAPIRequest) GetEnd() *int {
	if a == nil {
		return nil
	}
	return a.End
}

type AuthTokenGetListAPIResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	TokenGetListResponse *components.TokenGetListResponse
}

func (a AuthTokenGetListAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthTokenGetListAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthTokenGetListAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthTokenGetListAPIResponse) GetTokenGetListResponse() *components.TokenGetListResponse {
	if a == nil {
		return nil
	}
	return a.TokenGetListResponse
}
