// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthTokenCreateAPIRequest struct {
	// A service ID.
	ServiceID string                        `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.TokenCreateRequest `request:"mediaType=application/json"`
}

func (a *AuthTokenCreateAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthTokenCreateAPIRequest) GetBody() components.TokenCreateRequest {
	if a == nil {
		return components.TokenCreateRequest{}
	}
	return a.Body
}

type AuthTokenCreateAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Token created successfully
	TokenCreateResponse *components.TokenCreateResponse
}

func (a AuthTokenCreateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthTokenCreateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthTokenCreateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthTokenCreateAPIResponse) GetTokenCreateResponse() *components.TokenCreateResponse {
	if a == nil {
		return nil
	}
	return a.TokenCreateResponse
}
