// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthAuthorizationIssueAPIRequest struct {
	// A service ID.
	ServiceID string                               `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.AuthorizationIssueRequest `request:"mediaType=application/json"`
}

func (a *AuthAuthorizationIssueAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthAuthorizationIssueAPIRequest) GetBody() components.AuthorizationIssueRequest {
	if a == nil {
		return components.AuthorizationIssueRequest{}
	}
	return a.Body
}

type AuthAuthorizationIssueAPIResponse struct {
	HTTPMeta                   components.HTTPMetadata `json:"-"`
	AuthorizationIssueResponse *components.AuthorizationIssueResponse
}

func (a AuthAuthorizationIssueAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthAuthorizationIssueAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthAuthorizationIssueAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthAuthorizationIssueAPIResponse) GetAuthorizationIssueResponse() *components.AuthorizationIssueResponse {
	if a == nil {
		return nil
	}
	return a.AuthorizationIssueResponse
}
