// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthIntrospectionStandardAPIRequest struct {
	// A service ID.
	ServiceID string                                  `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.StandardIntrospectionRequest `request:"mediaType=application/json"`
}

func (a *AuthIntrospectionStandardAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthIntrospectionStandardAPIRequest) GetBody() components.StandardIntrospectionRequest {
	if a == nil {
		return components.StandardIntrospectionRequest{}
	}
	return a.Body
}

type AuthIntrospectionStandardAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Token introspection completed successfully
	StandardIntrospectionResponse *components.StandardIntrospectionResponse
}

func (a AuthIntrospectionStandardAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthIntrospectionStandardAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthIntrospectionStandardAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthIntrospectionStandardAPIResponse) GetStandardIntrospectionResponse() *components.StandardIntrospectionResponse {
	if a == nil {
		return nil
	}
	return a.StandardIntrospectionResponse
}
