// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthUserinfoIssueAPIRequest struct {
	// A service ID.
	ServiceID string                          `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.UserinfoIssueRequest `request:"mediaType=application/json"`
}

func (a *AuthUserinfoIssueAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthUserinfoIssueAPIRequest) GetBody() components.UserinfoIssueRequest {
	if a == nil {
		return components.UserinfoIssueRequest{}
	}
	return a.Body
}

type AuthUserinfoIssueAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User info issued successfully
	UserinfoIssueResponse *components.UserinfoIssueResponse
}

func (a AuthUserinfoIssueAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthUserinfoIssueAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthUserinfoIssueAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthUserinfoIssueAPIResponse) GetUserinfoIssueResponse() *components.UserinfoIssueResponse {
	if a == nil {
		return nil
	}
	return a.UserinfoIssueResponse
}
