// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type AuthRevocationAPIRequest struct {
	// A service ID.
	ServiceID string                       `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.RevocationRequest `request:"mediaType=application/json"`
}

func (a *AuthRevocationAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthRevocationAPIRequest) GetBody() components.RevocationRequest {
	if a == nil {
		return components.RevocationRequest{}
	}
	return a.Body
}

type AuthRevocationAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Token revoked successfully
	RevocationResponse *components.RevocationResponse
}

func (a AuthRevocationAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthRevocationAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthRevocationAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthRevocationAPIResponse) GetRevocationResponse() *components.RevocationResponse {
	if a == nil {
		return nil
	}
	return a.RevocationResponse
}
