// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type BackchannelAuthenticationFailAPIRequest struct {
	// A service ID.
	ServiceID string                                          `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.BackchannelAuthenticationFailRequest `request:"mediaType=application/json"`
}

func (b *BackchannelAuthenticationFailAPIRequest) GetServiceID() string {
	if b == nil {
		return ""
	}
	return b.ServiceID
}

func (b *BackchannelAuthenticationFailAPIRequest) GetBody() components.BackchannelAuthenticationFailRequest {
	if b == nil {
		return components.BackchannelAuthenticationFailRequest{}
	}
	return b.Body
}

type BackchannelAuthenticationFailAPIResponse struct {
	HTTPMeta                              components.HTTPMetadata `json:"-"`
	BackchannelAuthenticationFailResponse *components.BackchannelAuthenticationFailResponse
}

func (b BackchannelAuthenticationFailAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BackchannelAuthenticationFailAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BackchannelAuthenticationFailAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BackchannelAuthenticationFailAPIResponse) GetBackchannelAuthenticationFailResponse() *components.BackchannelAuthenticationFailResponse {
	if b == nil {
		return nil
	}
	return b.BackchannelAuthenticationFailResponse
}
