// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type BackchannelAuthenticationAPIRequest struct {
	// A service ID.
	ServiceID string                                      `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.BackchannelAuthenticationRequest `request:"mediaType=application/json"`
}

func (b *BackchannelAuthenticationAPIRequest) GetServiceID() string {
	if b == nil {
		return ""
	}
	return b.ServiceID
}

func (b *BackchannelAuthenticationAPIRequest) GetBody() components.BackchannelAuthenticationRequest {
	if b == nil {
		return components.BackchannelAuthenticationRequest{}
	}
	return b.Body
}

type BackchannelAuthenticationAPIResponse struct {
	HTTPMeta                          components.HTTPMetadata `json:"-"`
	BackchannelAuthenticationResponse *components.BackchannelAuthenticationResponse
}

func (b BackchannelAuthenticationAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BackchannelAuthenticationAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BackchannelAuthenticationAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BackchannelAuthenticationAPIResponse) GetBackchannelAuthenticationResponse() *components.BackchannelAuthenticationResponse {
	if b == nil {
		return nil
	}
	return b.BackchannelAuthenticationResponse
}
