// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientGrantedScopesGetAPIPostRequestBody struct {
	// Unique user ID of an end-user.
	Subject string `json:"subject"`
}

func (c *ClientGrantedScopesGetAPIPostRequestBody) GetSubject() string {
	if c == nil {
		return ""
	}
	return c.Subject
}

type ClientGrantedScopesGetAPIPostRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string                                   `pathParam:"style=simple,explode=false,name=clientId"`
	Body     ClientGrantedScopesGetAPIPostRequestBody `request:"mediaType=application/json"`
}

func (c *ClientGrantedScopesGetAPIPostRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientGrantedScopesGetAPIPostRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientGrantedScopesGetAPIPostRequest) GetBody() ClientGrantedScopesGetAPIPostRequestBody {
	if c == nil {
		return ClientGrantedScopesGetAPIPostRequestBody{}
	}
	return c.Body
}

type ClientGrantedScopesGetAPIPostResponse struct {
	HTTPMeta                          components.HTTPMetadata `json:"-"`
	ClientAuthorizationDeleteResponse *components.ClientAuthorizationDeleteResponse
}

func (c ClientGrantedScopesGetAPIPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientGrantedScopesGetAPIPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientGrantedScopesGetAPIPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientGrantedScopesGetAPIPostResponse) GetClientAuthorizationDeleteResponse() *components.ClientAuthorizationDeleteResponse {
	if c == nil {
		return nil
	}
	return c.ClientAuthorizationDeleteResponse
}
