// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientGrantedScopesDeleteAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
	// Unique user ID of an end-user.
	//
	Subject string `queryParam:"style=form,explode=true,name=subject"`
}

func (c *ClientGrantedScopesDeleteAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientGrantedScopesDeleteAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientGrantedScopesDeleteAPIRequest) GetSubject() string {
	if c == nil {
		return ""
	}
	return c.Subject
}

type ClientGrantedScopesDeleteAPIResponse struct {
	HTTPMeta                          components.HTTPMetadata `json:"-"`
	ClientGrantedScopesDeleteResponse *components.ClientGrantedScopesDeleteResponse
}

func (c ClientGrantedScopesDeleteAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientGrantedScopesDeleteAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientGrantedScopesDeleteAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientGrantedScopesDeleteAPIResponse) GetClientGrantedScopesDeleteResponse() *components.ClientGrantedScopesDeleteResponse {
	if c == nil {
		return nil
	}
	return c.ClientGrantedScopesDeleteResponse
}
