// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientGetListAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// The developer of client applications. The default value is null. If this parameter is not set
	// to `null`, client application of the specified developer are returned. Otherwise, all client
	// applications that belong to the service are returned.
	//
	Developer *string `queryParam:"style=form,explode=true,name=developer"`
	// Start index (inclusive) of the result set. The default value is 0. Must not be a negative number.
	Start *int `queryParam:"style=form,explode=true,name=start"`
	// End index (exclusive) of the result set. The default value is 5. Must not be a negative number.
	End *int `queryParam:"style=form,explode=true,name=end"`
}

func (c *ClientGetListAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientGetListAPIRequest) GetDeveloper() *string {
	if c == nil {
		return nil
	}
	return c.Developer
}

func (c *ClientGetListAPIRequest) GetStart() *int {
	if c == nil {
		return nil
	}
	return c.Start
}

func (c *ClientGetListAPIRequest) GetEnd() *int {
	if c == nil {
		return nil
	}
	return c.End
}

type ClientGetListAPIResponse struct {
	HTTPMeta              components.HTTPMetadata `json:"-"`
	ClientGetListResponse *components.ClientGetListResponse
}

func (c ClientGetListAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientGetListAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientGetListAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientGetListAPIResponse) GetClientGetListResponse() *components.ClientGetListResponse {
	if c == nil {
		return nil
	}
	return c.ClientGetListResponse
}
