// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientSecretUpdateAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// The client ID or the client ID alias of a client.
	//
	ClientIdentifier string                               `pathParam:"style=simple,explode=false,name=clientIdentifier"`
	Body             components.ClientSecretUpdateRequest `request:"mediaType=application/json"`
}

func (c *ClientSecretUpdateAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientSecretUpdateAPIRequest) GetClientIdentifier() string {
	if c == nil {
		return ""
	}
	return c.ClientIdentifier
}

func (c *ClientSecretUpdateAPIRequest) GetBody() components.ClientSecretUpdateRequest {
	if c == nil {
		return components.ClientSecretUpdateRequest{}
	}
	return c.Body
}

type ClientSecretUpdateAPIResponse struct {
	HTTPMeta                   components.HTTPMetadata `json:"-"`
	ClientSecretUpdateResponse *components.ClientSecretUpdateResponse
}

func (c ClientSecretUpdateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientSecretUpdateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientSecretUpdateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientSecretUpdateAPIResponse) GetClientSecretUpdateResponse() *components.ClientSecretUpdateResponse {
	if c == nil {
		return nil
	}
	return c.ClientSecretUpdateResponse
}
