// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientUpdateAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	ClientID string                  `pathParam:"style=simple,explode=false,name=clientId"`
	Body     *components.ClientInput `request:"mediaType=application/json"`
}

func (c ClientUpdateAPIRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientUpdateAPIRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientUpdateAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientUpdateAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientUpdateAPIRequest) GetBody() *components.ClientInput {
	if c == nil {
		return nil
	}
	return c.Body
}

type ClientUpdateAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Client   *components.Client
}

func (c ClientUpdateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientUpdateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientUpdateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientUpdateAPIResponse) GetClient() *components.Client {
	if c == nil {
		return nil
	}
	return c.Client
}
