// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientDeleteAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// The client ID.
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (c *ClientDeleteAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientDeleteAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

type ClientDeleteAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (c *ClientDeleteAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}
