// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientAuthorizationUpdateAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string                                       `pathParam:"style=simple,explode=false,name=clientId"`
	Body     *components.ClientAuthorizationUpdateRequest `request:"mediaType=application/json"`
}

func (c ClientAuthorizationUpdateAPIRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientAuthorizationUpdateAPIRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientAuthorizationUpdateAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientAuthorizationUpdateAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientAuthorizationUpdateAPIRequest) GetBody() *components.ClientAuthorizationUpdateRequest {
	if c == nil {
		return nil
	}
	return c.Body
}

type ClientAuthorizationUpdateAPIResponse struct {
	HTTPMeta                          components.HTTPMetadata `json:"-"`
	ClientAuthorizationUpdateResponse *components.ClientAuthorizationUpdateResponse
}

func (c ClientAuthorizationUpdateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientAuthorizationUpdateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientAuthorizationUpdateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientAuthorizationUpdateAPIResponse) GetClientAuthorizationUpdateResponse() *components.ClientAuthorizationUpdateResponse {
	if c == nil {
		return nil
	}
	return c.ClientAuthorizationUpdateResponse
}
