// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientAuthorizationDeleteAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
	// Unique user ID of an end-user.
	//
	Subject string `queryParam:"style=form,explode=true,name=subject"`
}

func (c *ClientAuthorizationDeleteAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientAuthorizationDeleteAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientAuthorizationDeleteAPIRequest) GetSubject() string {
	if c == nil {
		return ""
	}
	return c.Subject
}

type ClientAuthorizationDeleteAPIResponse struct {
	HTTPMeta                          components.HTTPMetadata `json:"-"`
	ClientAuthorizationDeleteResponse *components.ClientAuthorizationDeleteResponse
}

func (c ClientAuthorizationDeleteAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientAuthorizationDeleteAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientAuthorizationDeleteAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientAuthorizationDeleteAPIResponse) GetClientAuthorizationDeleteResponse() *components.ClientAuthorizationDeleteResponse {
	if c == nil {
		return nil
	}
	return c.ClientAuthorizationDeleteResponse
}
