// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientExtensionRequestablesScopesUpdateAPIPostRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string                                                   `pathParam:"style=simple,explode=false,name=clientId"`
	Body     components.ClientExtensionRequestableScopesUpdateRequest `request:"mediaType=application/json"`
}

func (c *ClientExtensionRequestablesScopesUpdateAPIPostRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientExtensionRequestablesScopesUpdateAPIPostRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientExtensionRequestablesScopesUpdateAPIPostRequest) GetBody() components.ClientExtensionRequestableScopesUpdateRequest {
	if c == nil {
		return components.ClientExtensionRequestableScopesUpdateRequest{}
	}
	return c.Body
}

type ClientExtensionRequestablesScopesUpdateAPIPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Requestable scopes updated successfully
	ClientExtensionRequestableScopesUpdateResponse *components.ClientExtensionRequestableScopesUpdateResponse
}

func (c ClientExtensionRequestablesScopesUpdateAPIPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientExtensionRequestablesScopesUpdateAPIPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientExtensionRequestablesScopesUpdateAPIPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientExtensionRequestablesScopesUpdateAPIPostResponse) GetClientExtensionRequestableScopesUpdateResponse() *components.ClientExtensionRequestableScopesUpdateResponse {
	if c == nil {
		return nil
	}
	return c.ClientExtensionRequestableScopesUpdateResponse
}
