// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientCreateAPIRequest struct {
	// A service ID.
	ServiceID string                  `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      *components.ClientInput `request:"mediaType=application/json"`
}

func (c ClientCreateAPIRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientCreateAPIRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientCreateAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientCreateAPIRequest) GetBody() *components.ClientInput {
	if c == nil {
		return nil
	}
	return c.Body
}

type ClientCreateAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Client created successfully (legacy compatibility)
	Client *components.Client
}

func (c ClientCreateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientCreateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientCreateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientCreateAPIResponse) GetClient() *components.Client {
	if c == nil {
		return nil
	}
	return c.Client
}
