// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientFlagUpdateAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	ClientIdentifier string                              `pathParam:"style=simple,explode=false,name=clientIdentifier"`
	Body             *components.ClientFlagUpdateRequest `request:"mediaType=application/json"`
}

func (c ClientFlagUpdateAPIRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientFlagUpdateAPIRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientFlagUpdateAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientFlagUpdateAPIRequest) GetClientIdentifier() string {
	if c == nil {
		return ""
	}
	return c.ClientIdentifier
}

func (c *ClientFlagUpdateAPIRequest) GetBody() *components.ClientFlagUpdateRequest {
	if c == nil {
		return nil
	}
	return c.Body
}

type ClientFlagUpdateAPIResponse struct {
	HTTPMeta                 components.HTTPMetadata `json:"-"`
	ClientFlagUpdateResponse *components.ClientFlagUpdateResponse
}

func (c ClientFlagUpdateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientFlagUpdateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientFlagUpdateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientFlagUpdateAPIResponse) GetClientFlagUpdateResponse() *components.ClientFlagUpdateResponse {
	if c == nil {
		return nil
	}
	return c.ClientFlagUpdateResponse
}
