// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientUpdateAPIFormRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	ClientID string         `pathParam:"style=simple,explode=false,name=clientId"`
	Body     map[string]any `request:"mediaType=application/x-www-form-urlencoded"`
}

func (c ClientUpdateAPIFormRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientUpdateAPIFormRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientUpdateAPIFormRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientUpdateAPIFormRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientUpdateAPIFormRequest) GetBody() map[string]any {
	if c == nil {
		return nil
	}
	return c.Body
}

type ClientUpdateAPIFormResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Client   *components.Client
}

func (c ClientUpdateAPIFormResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientUpdateAPIFormResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientUpdateAPIFormResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientUpdateAPIFormResponse) GetClient() *components.Client {
	if c == nil {
		return nil
	}
	return c.Client
}
