// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientAuthorizationGetListBySubjectAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// Unique user ID of an end-user.
	//
	Subject string `pathParam:"style=simple,explode=false,name=subject"`
	// Unique ID of a client developer.
	//
	Developer *string `queryParam:"style=form,explode=true,name=developer"`
	// Start index of search results (inclusive). The default value is 0.
	Start *int `queryParam:"style=form,explode=true,name=start"`
	// End index of search results (exclusive). The default value is 5.
	//
	End *int `queryParam:"style=form,explode=true,name=end"`
}

func (c *ClientAuthorizationGetListBySubjectAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientAuthorizationGetListBySubjectAPIRequest) GetSubject() string {
	if c == nil {
		return ""
	}
	return c.Subject
}

func (c *ClientAuthorizationGetListBySubjectAPIRequest) GetDeveloper() *string {
	if c == nil {
		return nil
	}
	return c.Developer
}

func (c *ClientAuthorizationGetListBySubjectAPIRequest) GetStart() *int {
	if c == nil {
		return nil
	}
	return c.Start
}

func (c *ClientAuthorizationGetListBySubjectAPIRequest) GetEnd() *int {
	if c == nil {
		return nil
	}
	return c.End
}

type ClientAuthorizationGetListBySubjectAPIResponse struct {
	HTTPMeta                           components.HTTPMetadata `json:"-"`
	ClientAuthorizationGetListResponse *components.ClientAuthorizationGetListResponse
}

func (c ClientAuthorizationGetListBySubjectAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientAuthorizationGetListBySubjectAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientAuthorizationGetListBySubjectAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientAuthorizationGetListBySubjectAPIResponse) GetClientAuthorizationGetListResponse() *components.ClientAuthorizationGetListResponse {
	if c == nil {
		return nil
	}
	return c.ClientAuthorizationGetListResponse
}
