// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientAuthorizationDeleteAPIPostRequestBody struct {
	// Unique user ID of an end-user.
	Subject string `json:"subject"`
}

func (c *ClientAuthorizationDeleteAPIPostRequestBody) GetSubject() string {
	if c == nil {
		return ""
	}
	return c.Subject
}

type ClientAuthorizationDeleteAPIPostRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string                                      `pathParam:"style=simple,explode=false,name=clientId"`
	Body     ClientAuthorizationDeleteAPIPostRequestBody `request:"mediaType=application/json"`
}

func (c *ClientAuthorizationDeleteAPIPostRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientAuthorizationDeleteAPIPostRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientAuthorizationDeleteAPIPostRequest) GetBody() ClientAuthorizationDeleteAPIPostRequestBody {
	if c == nil {
		return ClientAuthorizationDeleteAPIPostRequestBody{}
	}
	return c.Body
}

type ClientAuthorizationDeleteAPIPostResponse struct {
	HTTPMeta                          components.HTTPMetadata `json:"-"`
	ClientAuthorizationDeleteResponse *components.ClientAuthorizationDeleteResponse
}

func (c ClientAuthorizationDeleteAPIPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientAuthorizationDeleteAPIPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientAuthorizationDeleteAPIPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientAuthorizationDeleteAPIPostResponse) GetClientAuthorizationDeleteResponse() *components.ClientAuthorizationDeleteResponse {
	if c == nil {
		return nil
	}
	return c.ClientAuthorizationDeleteResponse
}
