// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientRegistrationUpdateAPIRequestBody struct {
	// Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
	// (OAuth 2.0 Dynamic Client Registration Protocol).
	//
	JSON string `json:"json"`
	// The client registration access token. Used only for GET, UPDATE, and DELETE requests.
	//
	Token string `json:"token"`
	// The client's identifier. Used for GET, UPDATE, and DELETE requests
	//
	ClientID string `json:"clientId"`
}

func (c *ClientRegistrationUpdateAPIRequestBody) GetJSON() string {
	if c == nil {
		return ""
	}
	return c.JSON
}

func (c *ClientRegistrationUpdateAPIRequestBody) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *ClientRegistrationUpdateAPIRequestBody) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

type ClientRegistrationUpdateAPIRequest struct {
	// A service ID.
	ServiceID string                                 `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      ClientRegistrationUpdateAPIRequestBody `request:"mediaType=application/json"`
}

func (c *ClientRegistrationUpdateAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientRegistrationUpdateAPIRequest) GetBody() ClientRegistrationUpdateAPIRequestBody {
	if c == nil {
		return ClientRegistrationUpdateAPIRequestBody{}
	}
	return c.Body
}

type ClientRegistrationUpdateAPIResponse struct {
	HTTPMeta                   components.HTTPMetadata `json:"-"`
	ClientRegistrationResponse *components.ClientRegistrationResponse
}

func (c ClientRegistrationUpdateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientRegistrationUpdateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientRegistrationUpdateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientRegistrationUpdateAPIResponse) GetClientRegistrationResponse() *components.ClientRegistrationResponse {
	if c == nil {
		return nil
	}
	return c.ClientRegistrationResponse
}
