// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientExtensionRequestablesScopesGetAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (c *ClientExtensionRequestablesScopesGetAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientExtensionRequestablesScopesGetAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

type ClientExtensionRequestablesScopesGetAPIResponse struct {
	HTTPMeta                                    components.HTTPMetadata `json:"-"`
	ClientExtensionRequestableScopesGetResponse *components.ClientExtensionRequestableScopesGetResponse
}

func (c ClientExtensionRequestablesScopesGetAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientExtensionRequestablesScopesGetAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientExtensionRequestablesScopesGetAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientExtensionRequestablesScopesGetAPIResponse) GetClientExtensionRequestableScopesGetResponse() *components.ClientExtensionRequestableScopesGetResponse {
	if c == nil {
		return nil
	}
	return c.ClientExtensionRequestableScopesGetResponse
}
