// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientRegistrationAPIRequestBody struct {
	// Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
	// (OAuth 2.0 Dynamic Client Registration Protocol).
	//
	JSON string `json:"json"`
	// The client registration access token. Used only for GET, UPDATE, and DELETE requests.
	//
	Token *string `json:"token,omitzero"`
	// The client's identifier. Used for GET, UPDATE, and DELETE requests
	//
	ClientID *string `json:"clientId,omitzero"`
}

func (c *ClientRegistrationAPIRequestBody) GetJSON() string {
	if c == nil {
		return ""
	}
	return c.JSON
}

func (c *ClientRegistrationAPIRequestBody) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}

func (c *ClientRegistrationAPIRequestBody) GetClientID() *string {
	if c == nil {
		return nil
	}
	return c.ClientID
}

type ClientRegistrationAPIRequest struct {
	// A service ID.
	ServiceID string                           `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      ClientRegistrationAPIRequestBody `request:"mediaType=application/json"`
}

func (c *ClientRegistrationAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientRegistrationAPIRequest) GetBody() ClientRegistrationAPIRequestBody {
	if c == nil {
		return ClientRegistrationAPIRequestBody{}
	}
	return c.Body
}

type ClientRegistrationAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Client registration completed successfully
	ClientRegistrationResponse *components.ClientRegistrationResponse
}

func (c ClientRegistrationAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientRegistrationAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientRegistrationAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientRegistrationAPIResponse) GetClientRegistrationResponse() *components.ClientRegistrationResponse {
	if c == nil {
		return nil
	}
	return c.ClientRegistrationResponse
}
