// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientGetAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (c *ClientGetAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientGetAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

type ClientGetAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Client   *components.Client
}

func (c ClientGetAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientGetAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientGetAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientGetAPIResponse) GetClient() *components.Client {
	if c == nil {
		return nil
	}
	return c.Client
}
