// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ClientExtensionRequestablesScopesDeleteAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (c *ClientExtensionRequestablesScopesDeleteAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientExtensionRequestablesScopesDeleteAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

type ClientExtensionRequestablesScopesDeleteAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (c *ClientExtensionRequestablesScopesDeleteAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}
