// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type DeviceAuthorizationAPIRequest struct {
	// A service ID.
	ServiceID string                                `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.DeviceAuthorizationRequest `request:"mediaType=application/json"`
}

func (d *DeviceAuthorizationAPIRequest) GetServiceID() string {
	if d == nil {
		return ""
	}
	return d.ServiceID
}

func (d *DeviceAuthorizationAPIRequest) GetBody() components.DeviceAuthorizationRequest {
	if d == nil {
		return components.DeviceAuthorizationRequest{}
	}
	return d.Body
}

type DeviceAuthorizationAPIResponse struct {
	HTTPMeta                    components.HTTPMetadata `json:"-"`
	DeviceAuthorizationResponse *components.DeviceAuthorizationResponse
}

func (d DeviceAuthorizationAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeviceAuthorizationAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeviceAuthorizationAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeviceAuthorizationAPIResponse) GetDeviceAuthorizationResponse() *components.DeviceAuthorizationResponse {
	if d == nil {
		return nil
	}
	return d.DeviceAuthorizationResponse
}
