// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type DeviceCompleteAPIRequest struct {
	// A service ID.
	ServiceID string                           `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.DeviceCompleteRequest `request:"mediaType=application/json"`
}

func (d *DeviceCompleteAPIRequest) GetServiceID() string {
	if d == nil {
		return ""
	}
	return d.ServiceID
}

func (d *DeviceCompleteAPIRequest) GetBody() components.DeviceCompleteRequest {
	if d == nil {
		return components.DeviceCompleteRequest{}
	}
	return d.Body
}

type DeviceCompleteAPIResponse struct {
	HTTPMeta               components.HTTPMetadata `json:"-"`
	DeviceCompleteResponse *components.DeviceCompleteResponse
}

func (d DeviceCompleteAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeviceCompleteAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeviceCompleteAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeviceCompleteAPIResponse) GetDeviceCompleteResponse() *components.DeviceCompleteResponse {
	if d == nil {
		return nil
	}
	return d.DeviceCompleteResponse
}
