// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type DeviceVerificationAPIRequest struct {
	// A service ID.
	ServiceID string                               `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.DeviceVerificationRequest `request:"mediaType=application/json"`
}

func (d *DeviceVerificationAPIRequest) GetServiceID() string {
	if d == nil {
		return ""
	}
	return d.ServiceID
}

func (d *DeviceVerificationAPIRequest) GetBody() components.DeviceVerificationRequest {
	if d == nil {
		return components.DeviceVerificationRequest{}
	}
	return d.Body
}

type DeviceVerificationAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Device verification completed successfully
	DeviceVerificationResponse *components.DeviceVerificationResponse
}

func (d DeviceVerificationAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeviceVerificationAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeviceVerificationAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeviceVerificationAPIResponse) GetDeviceVerificationResponse() *components.DeviceVerificationResponse {
	if d == nil {
		return nil
	}
	return d.DeviceVerificationResponse
}
