// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type FederationConfigurationAPIRequestBody struct {
}

type FederationConfigurationAPIRequest struct {
	// A service ID.
	ServiceID string                                 `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      *FederationConfigurationAPIRequestBody `request:"mediaType=application/json"`
}

func (f FederationConfigurationAPIRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FederationConfigurationAPIRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FederationConfigurationAPIRequest) GetServiceID() string {
	if f == nil {
		return ""
	}
	return f.ServiceID
}

func (f *FederationConfigurationAPIRequest) GetBody() *FederationConfigurationAPIRequestBody {
	if f == nil {
		return nil
	}
	return f.Body
}

type FederationConfigurationAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Federation configuration retrieved successfully
	FederationConfigurationResponse *components.FederationConfigurationResponse
}

func (f FederationConfigurationAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FederationConfigurationAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FederationConfigurationAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FederationConfigurationAPIResponse) GetFederationConfigurationResponse() *components.FederationConfigurationResponse {
	if f == nil {
		return nil
	}
	return f.FederationConfigurationResponse
}
