// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type GetAuthorizationTicketInfoRequest struct {
	// A service ID.
	ServiceID string                                    `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.AuthorizationTicketInfoRequest `request:"mediaType=application/json"`
}

func (g *GetAuthorizationTicketInfoRequest) GetServiceID() string {
	if g == nil {
		return ""
	}
	return g.ServiceID
}

func (g *GetAuthorizationTicketInfoRequest) GetBody() components.AuthorizationTicketInfoRequest {
	if g == nil {
		return components.AuthorizationTicketInfoRequest{}
	}
	return g.Body
}

type GetAuthorizationTicketInfoResponse struct {
	HTTPMeta                        components.HTTPMetadata `json:"-"`
	AuthorizationTicketInfoResponse *components.AuthorizationTicketInfoResponse
}

func (g GetAuthorizationTicketInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAuthorizationTicketInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAuthorizationTicketInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAuthorizationTicketInfoResponse) GetAuthorizationTicketInfoResponse() *components.AuthorizationTicketInfoResponse {
	if g == nil {
		return nil
	}
	return g.AuthorizationTicketInfoResponse
}
