// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/models/components"
)

type GetAPILifecycleHealthcheckRequest struct {
	// If `true`, perform extended health checks (e.g. database connectivity).
	//
	Extended *bool `queryParam:"style=form,explode=true,name=extended"`
}

func (g *GetAPILifecycleHealthcheckRequest) GetExtended() *bool {
	if g == nil {
		return nil
	}
	return g.Extended
}

type GetAPILifecycleHealthcheckResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Res *string
}

func (g *GetAPILifecycleHealthcheckResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAPILifecycleHealthcheckResponse) GetRes() *string {
	if g == nil {
		return nil
	}
	return g.Res
}
