// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type GrantMAPIRequest struct {
	// A service ID.
	ServiceID string               `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.GMRequest `request:"mediaType=application/json"`
}

func (g *GrantMAPIRequest) GetServiceID() string {
	if g == nil {
		return ""
	}
	return g.ServiceID
}

func (g *GrantMAPIRequest) GetBody() components.GMRequest {
	if g == nil {
		return components.GMRequest{}
	}
	return g.Body
}

type GrantMAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Grant management completed successfully
	GMResponse *components.GMResponse
}

func (g GrantMAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GrantMAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GrantMAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GrantMAPIResponse) GetGMResponse() *components.GMResponse {
	if g == nil {
		return nil
	}
	return g.GMResponse
}
