// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type HskDeleteAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	Handle    string `pathParam:"style=simple,explode=false,name=handle"`
}

func (h *HskDeleteAPIRequest) GetServiceID() string {
	if h == nil {
		return ""
	}
	return h.ServiceID
}

func (h *HskDeleteAPIRequest) GetHandle() string {
	if h == nil {
		return ""
	}
	return h.Handle
}

type HskDeleteAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// HSK deleted successfully
	HskDeleteResponse *components.HskDeleteResponse
}

func (h HskDeleteAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HskDeleteAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HskDeleteAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HskDeleteAPIResponse) GetHskDeleteResponse() *components.HskDeleteResponse {
	if h == nil {
		return nil
	}
	return h.HskDeleteResponse
}
