// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type HskGetAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	Handle    string `pathParam:"style=simple,explode=false,name=handle"`
}

func (h *HskGetAPIRequest) GetServiceID() string {
	if h == nil {
		return ""
	}
	return h.ServiceID
}

func (h *HskGetAPIRequest) GetHandle() string {
	if h == nil {
		return ""
	}
	return h.Handle
}

type HskGetAPIResponse struct {
	HTTPMeta       components.HTTPMetadata `json:"-"`
	HskGetResponse *components.HskGetResponse
}

func (h HskGetAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HskGetAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HskGetAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HskGetAPIResponse) GetHskGetResponse() *components.HskGetResponse {
	if h == nil {
		return nil
	}
	return h.HskGetResponse
}
