// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type HskGetListAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
}

func (h *HskGetListAPIRequest) GetServiceID() string {
	if h == nil {
		return ""
	}
	return h.ServiceID
}

type HskGetListAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// HSK list retrieved successfully
	HskGetListResponse *components.HskGetListResponse
}

func (h HskGetListAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HskGetListAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HskGetListAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HskGetListAPIResponse) GetHskGetListResponse() *components.HskGetListResponse {
	if h == nil {
		return nil
	}
	return h.HskGetListResponse
}
