// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type JoseVerifyAPIRequest struct {
	// A service ID.
	ServiceID string                        `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      *components.JoseVerifyRequest `request:"mediaType=application/json"`
}

func (j JoseVerifyAPIRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JoseVerifyAPIRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *JoseVerifyAPIRequest) GetServiceID() string {
	if j == nil {
		return ""
	}
	return j.ServiceID
}

func (j *JoseVerifyAPIRequest) GetBody() *components.JoseVerifyRequest {
	if j == nil {
		return nil
	}
	return j.Body
}

type JoseVerifyAPIResponse struct {
	HTTPMeta           components.HTTPMetadata `json:"-"`
	JoseVerifyResponse *components.JoseVerifyResponse
}

func (j JoseVerifyAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JoseVerifyAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *JoseVerifyAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if j == nil {
		return components.HTTPMetadata{}
	}
	return j.HTTPMeta
}

func (j *JoseVerifyAPIResponse) GetJoseVerifyResponse() *components.JoseVerifyResponse {
	if j == nil {
		return nil
	}
	return j.JoseVerifyResponse
}
