// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type NativeSsoAPIRequest struct {
	// A service ID.
	ServiceID string                      `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.NativeSsoRequest `request:"mediaType=application/json"`
}

func (n *NativeSsoAPIRequest) GetServiceID() string {
	if n == nil {
		return ""
	}
	return n.ServiceID
}

func (n *NativeSsoAPIRequest) GetBody() components.NativeSsoRequest {
	if n == nil {
		return components.NativeSsoRequest{}
	}
	return n.Body
}

type NativeSsoAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Native SSO processing completed successfully
	NativeSsoResponse *components.NativeSsoResponse
}

func (n NativeSsoAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NativeSsoAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NativeSsoAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if n == nil {
		return components.HTTPMetadata{}
	}
	return n.HTTPMeta
}

func (n *NativeSsoAPIResponse) GetNativeSsoResponse() *components.NativeSsoResponse {
	if n == nil {
		return nil
	}
	return n.NativeSsoResponse
}
