// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type NativeSsoLogoutAPIRequest struct {
	// A service ID.
	ServiceID string                            `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.NativeSsoLogoutRequest `request:"mediaType=application/json"`
}

func (n *NativeSsoLogoutAPIRequest) GetServiceID() string {
	if n == nil {
		return ""
	}
	return n.ServiceID
}

func (n *NativeSsoLogoutAPIRequest) GetBody() components.NativeSsoLogoutRequest {
	if n == nil {
		return components.NativeSsoLogoutRequest{}
	}
	return n.Body
}

type NativeSsoLogoutAPIResponse struct {
	HTTPMeta                components.HTTPMetadata `json:"-"`
	NativeSsoLogoutResponse *components.NativeSsoLogoutResponse
}

func (n NativeSsoLogoutAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NativeSsoLogoutAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NativeSsoLogoutAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if n == nil {
		return components.HTTPMetadata{}
	}
	return n.HTTPMeta
}

func (n *NativeSsoLogoutAPIResponse) GetNativeSsoLogoutResponse() *components.NativeSsoLogoutResponse {
	if n == nil {
		return nil
	}
	return n.NativeSsoLogoutResponse
}
