// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type PushedAuthReqAPIRequest struct {
	// A service ID.
	ServiceID string                                `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.PushedAuthorizationRequest `request:"mediaType=application/json"`
}

func (p *PushedAuthReqAPIRequest) GetServiceID() string {
	if p == nil {
		return ""
	}
	return p.ServiceID
}

func (p *PushedAuthReqAPIRequest) GetBody() components.PushedAuthorizationRequest {
	if p == nil {
		return components.PushedAuthorizationRequest{}
	}
	return p.Body
}

type PushedAuthReqAPIResponse struct {
	HTTPMeta                    components.HTTPMetadata `json:"-"`
	PushedAuthorizationResponse *components.PushedAuthorizationResponse
}

func (p PushedAuthReqAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PushedAuthReqAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PushedAuthReqAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PushedAuthReqAPIResponse) GetPushedAuthorizationResponse() *components.PushedAuthorizationResponse {
	if p == nil {
		return nil
	}
	return p.PushedAuthorizationResponse
}
