// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ServiceDeleteAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
}

func (s *ServiceDeleteAPIRequest) GetServiceID() string {
	if s == nil {
		return ""
	}
	return s.ServiceID
}

type ServiceDeleteAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (s *ServiceDeleteAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}
