// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ServiceGetListAPIRequest struct {
	// Start index (inclusive) of the result set. The default value is 0. Must not be a negative number.
	Start *int `queryParam:"style=form,explode=true,name=start"`
	// End index (exclusive) of the result set. The default value is 5. Must not be a negative number.
	End *int `queryParam:"style=form,explode=true,name=end"`
}

func (s *ServiceGetListAPIRequest) GetStart() *int {
	if s == nil {
		return nil
	}
	return s.Start
}

func (s *ServiceGetListAPIRequest) GetEnd() *int {
	if s == nil {
		return nil
	}
	return s.End
}

type ServiceGetListAPIResponse struct {
	HTTPMeta               components.HTTPMetadata `json:"-"`
	ServiceGetListResponse *components.ServiceGetListResponse
}

func (s ServiceGetListAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServiceGetListAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServiceGetListAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *ServiceGetListAPIResponse) GetServiceGetListResponse() *components.ServiceGetListResponse {
	if s == nil {
		return nil
	}
	return s.ServiceGetListResponse
}
