// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ServiceUpdateAPIRequest struct {
	// A service ID.
	ServiceID string                   `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      *components.ServiceInput `request:"mediaType=application/json"`
}

func (s ServiceUpdateAPIRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServiceUpdateAPIRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServiceUpdateAPIRequest) GetServiceID() string {
	if s == nil {
		return ""
	}
	return s.ServiceID
}

func (s *ServiceUpdateAPIRequest) GetBody() *components.ServiceInput {
	if s == nil {
		return nil
	}
	return s.Body
}

type ServiceUpdateAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Service  *components.Service
}

func (s ServiceUpdateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServiceUpdateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServiceUpdateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *ServiceUpdateAPIResponse) GetService() *components.Service {
	if s == nil {
		return nil
	}
	return s.Service
}
