// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type UpdateAuthorizationTicketRequest struct {
	// A service ID.
	ServiceID string                                      `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.AuthorizationTicketUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateAuthorizationTicketRequest) GetServiceID() string {
	if u == nil {
		return ""
	}
	return u.ServiceID
}

func (u *UpdateAuthorizationTicketRequest) GetBody() components.AuthorizationTicketUpdateRequest {
	if u == nil {
		return components.AuthorizationTicketUpdateRequest{}
	}
	return u.Body
}

type UpdateAuthorizationTicketResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Authorization ticket updated successfully
	AuthorizationTicketUpdateResponse *components.AuthorizationTicketUpdateResponse
}

func (u UpdateAuthorizationTicketResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAuthorizationTicketResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAuthorizationTicketResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAuthorizationTicketResponse) GetAuthorizationTicketUpdateResponse() *components.AuthorizationTicketUpdateResponse {
	if u == nil {
		return nil
	}
	return u.AuthorizationTicketUpdateResponse
}
