// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type VciBatchIssueAPIRequest struct {
	// A service ID.
	ServiceID string                          `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.VciBatchIssueRequest `request:"mediaType=application/json"`
}

func (v *VciBatchIssueAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciBatchIssueAPIRequest) GetBody() components.VciBatchIssueRequest {
	if v == nil {
		return components.VciBatchIssueRequest{}
	}
	return v.Body
}

type VciBatchIssueAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Batch credential issuance completed successfully
	VciBatchIssueResponse *components.VciBatchIssueResponse
}

func (v VciBatchIssueAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciBatchIssueAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciBatchIssueAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VciBatchIssueAPIResponse) GetVciBatchIssueResponse() *components.VciBatchIssueResponse {
	if v == nil {
		return nil
	}
	return v.VciBatchIssueResponse
}
