// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type VciBatchParseAPIRequest struct {
	// A service ID.
	ServiceID string                          `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.VciBatchParseRequest `request:"mediaType=application/json"`
}

func (v *VciBatchParseAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciBatchParseAPIRequest) GetBody() components.VciBatchParseRequest {
	if v == nil {
		return components.VciBatchParseRequest{}
	}
	return v.Body
}

type VciBatchParseAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Batch credential parsing completed successfully
	VciBatchParseResponse *components.VciBatchParseResponse
}

func (v VciBatchParseAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciBatchParseAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciBatchParseAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VciBatchParseAPIResponse) GetVciBatchParseResponse() *components.VciBatchParseResponse {
	if v == nil {
		return nil
	}
	return v.VciBatchParseResponse
}
