// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type VciDeferredIssueAPIRequest struct {
	// A service ID.
	ServiceID string                             `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.VciDeferredIssueRequest `request:"mediaType=application/json"`
}

func (v *VciDeferredIssueAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciDeferredIssueAPIRequest) GetBody() components.VciDeferredIssueRequest {
	if v == nil {
		return components.VciDeferredIssueRequest{}
	}
	return v.Body
}

type VciDeferredIssueAPIResponse struct {
	HTTPMeta                 components.HTTPMetadata `json:"-"`
	VciDeferredIssueResponse *components.VciDeferredIssueResponse
}

func (v VciDeferredIssueAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciDeferredIssueAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciDeferredIssueAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VciDeferredIssueAPIResponse) GetVciDeferredIssueResponse() *components.VciDeferredIssueResponse {
	if v == nil {
		return nil
	}
	return v.VciDeferredIssueResponse
}
