// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type VciDeferredParseAPIRequest struct {
	// A service ID.
	ServiceID string                             `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.VciDeferredParseRequest `request:"mediaType=application/json"`
}

func (v *VciDeferredParseAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciDeferredParseAPIRequest) GetBody() components.VciDeferredParseRequest {
	if v == nil {
		return components.VciDeferredParseRequest{}
	}
	return v.Body
}

type VciDeferredParseAPIResponse struct {
	HTTPMeta                 components.HTTPMetadata `json:"-"`
	VciDeferredParseResponse *components.VciDeferredParseResponse
}

func (v VciDeferredParseAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciDeferredParseAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciDeferredParseAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VciDeferredParseAPIResponse) GetVciDeferredParseResponse() *components.VciDeferredParseResponse {
	if v == nil {
		return nil
	}
	return v.VciDeferredParseResponse
}
