// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type VciJwtissuerAPIRequest struct {
	// A service ID.
	ServiceID string                         `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.VciJwtissuerRequest `request:"mediaType=application/json"`
}

func (v *VciJwtissuerAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciJwtissuerAPIRequest) GetBody() components.VciJwtissuerRequest {
	if v == nil {
		return components.VciJwtissuerRequest{}
	}
	return v.Body
}

type VciJwtissuerAPIResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	VciJwtissuerResponse *components.VciJwtissuerResponse
}

func (v VciJwtissuerAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciJwtissuerAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciJwtissuerAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VciJwtissuerAPIResponse) GetVciJwtissuerResponse() *components.VciJwtissuerResponse {
	if v == nil {
		return nil
	}
	return v.VciJwtissuerResponse
}
