// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type VciJwksAPIRequest struct {
	// A service ID.
	ServiceID string                    `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.VciJwksRequest `request:"mediaType=application/json"`
}

func (v *VciJwksAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciJwksAPIRequest) GetBody() components.VciJwksRequest {
	if v == nil {
		return components.VciJwksRequest{}
	}
	return v.Body
}

type VciJwksAPIResponse struct {
	HTTPMeta        components.HTTPMetadata `json:"-"`
	VciJwksResponse *components.VciJwksResponse
}

func (v VciJwksAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciJwksAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciJwksAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VciJwksAPIResponse) GetVciJwksResponse() *components.VciJwksResponse {
	if v == nil {
		return nil
	}
	return v.VciJwksResponse
}
