// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type VciOfferInfoAPIRequest struct {
	// A service ID.
	ServiceID string                         `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.VciOfferInfoRequest `request:"mediaType=application/json"`
}

func (v *VciOfferInfoAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciOfferInfoAPIRequest) GetBody() components.VciOfferInfoRequest {
	if v == nil {
		return components.VciOfferInfoRequest{}
	}
	return v.Body
}

type VciOfferInfoAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Credential offer info retrieved successfully
	VciOfferInfoResponse *components.VciOfferInfoResponse
}

func (v VciOfferInfoAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciOfferInfoAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciOfferInfoAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VciOfferInfoAPIResponse) GetVciOfferInfoResponse() *components.VciOfferInfoResponse {
	if v == nil {
		return nil
	}
	return v.VciOfferInfoResponse
}
