// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type VciOfferCreateAPIRequest struct {
	// A service ID.
	ServiceID string                           `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.VciOfferCreateRequest `request:"mediaType=application/json"`
}

func (v *VciOfferCreateAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciOfferCreateAPIRequest) GetBody() components.VciOfferCreateRequest {
	if v == nil {
		return components.VciOfferCreateRequest{}
	}
	return v.Body
}

type VciOfferCreateAPIResponse struct {
	HTTPMeta               components.HTTPMetadata `json:"-"`
	VciOfferCreateResponse *components.VciOfferCreateResponse
}

func (v VciOfferCreateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciOfferCreateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciOfferCreateAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VciOfferCreateAPIResponse) GetVciOfferCreateResponse() *components.VciOfferCreateResponse {
	if v == nil {
		return nil
	}
	return v.VciOfferCreateResponse
}
