// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type VciSingleParseAPIRequest struct {
	// A service ID.
	ServiceID string                           `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      components.VciSingleParseRequest `request:"mediaType=application/json"`
}

func (v *VciSingleParseAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciSingleParseAPIRequest) GetBody() components.VciSingleParseRequest {
	if v == nil {
		return components.VciSingleParseRequest{}
	}
	return v.Body
}

type VciSingleParseAPIResponse struct {
	HTTPMeta               components.HTTPMetadata `json:"-"`
	VciSingleParseResponse *components.VciSingleParseResponse
}

func (v VciSingleParseAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciSingleParseAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciSingleParseAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VciSingleParseAPIResponse) GetVciSingleParseResponse() *components.VciSingleParseResponse {
	if v == nil {
		return nil
	}
	return v.VciSingleParseResponse
}
