// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ApplicationType - The application type. The value of this property affects the validation steps for a redirect URI.
// See the description about `redirectUris` property for more details.
type ApplicationType string

const (
	ApplicationTypeWeb    ApplicationType = "WEB"
	ApplicationTypeNative ApplicationType = "NATIVE"
)

func (e ApplicationType) ToPointer() *ApplicationType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ApplicationType) IsExact() bool {
	if e != nil {
		switch *e {
		case "WEB", "NATIVE":
			return true
		}
	}
	return false
}
