// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AttachmentType - Supported attachment types. This property corresponds to the `attachments_supported`
//
//	server metadata which was added by the third implementer's draft of OpenID Connect
//	for Identity Assurance 1.0.
type AttachmentType string

const (
	AttachmentTypeEmbedded AttachmentType = "EMBEDDED"
	AttachmentTypeExternal AttachmentType = "EXTERNAL"
)

func (e AttachmentType) ToPointer() *AttachmentType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AttachmentType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EMBEDDED", "EXTERNAL":
			return true
		}
	}
	return false
}
