// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuthorizationFailResponseAction - The next action that the authorization server implementation should take.
type AuthorizationFailResponseAction string

const (
	AuthorizationFailResponseActionInternalServerError AuthorizationFailResponseAction = "INTERNAL_SERVER_ERROR"
	AuthorizationFailResponseActionBadRequest          AuthorizationFailResponseAction = "BAD_REQUEST"
	AuthorizationFailResponseActionLocation            AuthorizationFailResponseAction = "LOCATION"
	AuthorizationFailResponseActionForm                AuthorizationFailResponseAction = "FORM"
)

func (e AuthorizationFailResponseAction) ToPointer() *AuthorizationFailResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AuthorizationFailResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "INTERNAL_SERVER_ERROR", "BAD_REQUEST", "LOCATION", "FORM":
			return true
		}
	}
	return false
}

type AuthorizationFailResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *AuthorizationFailResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation is to return to the client application.
	// Its format varies depending on the value of `action` parameter.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (a *AuthorizationFailResponse) GetResultCode() *string {
	if a == nil {
		return nil
	}
	return a.ResultCode
}

func (a *AuthorizationFailResponse) GetResultMessage() *string {
	if a == nil {
		return nil
	}
	return a.ResultMessage
}

func (a *AuthorizationFailResponse) GetAction() *AuthorizationFailResponseAction {
	if a == nil {
		return nil
	}
	return a.Action
}

func (a *AuthorizationFailResponse) GetResponseContent() *string {
	if a == nil {
		return nil
	}
	return a.ResponseContent
}
