// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

// AuthorizationTicketUpdateResponseAction - The result of the /auth/authorization/ticket/info API call.
type AuthorizationTicketUpdateResponseAction string

const (
	AuthorizationTicketUpdateResponseActionOk            AuthorizationTicketUpdateResponseAction = "OK"
	AuthorizationTicketUpdateResponseActionNotFound      AuthorizationTicketUpdateResponseAction = "NOT_FOUND"
	AuthorizationTicketUpdateResponseActionCallerError   AuthorizationTicketUpdateResponseAction = "CALLER_ERROR"
	AuthorizationTicketUpdateResponseActionAuthleteError AuthorizationTicketUpdateResponseAction = "AUTHLETE_ERROR"
)

func (e AuthorizationTicketUpdateResponseAction) ToPointer() *AuthorizationTicketUpdateResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AuthorizationTicketUpdateResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "NOT_FOUND", "CALLER_ERROR", "AUTHLETE_ERROR":
			return true
		}
	}
	return false
}

type AuthorizationTicketUpdateResponse struct {
	Info *AuthorizationTicketInfo `json:"info,omitzero"`
	// The result of the /auth/authorization/ticket/info API call.
	Action *AuthorizationTicketUpdateResponseAction `json:"action,omitzero"`
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
}

func (a AuthorizationTicketUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthorizationTicketUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthorizationTicketUpdateResponse) GetInfo() *AuthorizationTicketInfo {
	if a == nil {
		return nil
	}
	return a.Info
}

func (a *AuthorizationTicketUpdateResponse) GetAction() *AuthorizationTicketUpdateResponseAction {
	if a == nil {
		return nil
	}
	return a.Action
}

func (a *AuthorizationTicketUpdateResponse) GetResultCode() *string {
	if a == nil {
		return nil
	}
	return a.ResultCode
}

func (a *AuthorizationTicketUpdateResponse) GetResultMessage() *string {
	if a == nil {
		return nil
	}
	return a.ResultMessage
}
