// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ClaimType string

const (
	ClaimTypeNormal      ClaimType = "NORMAL"
	ClaimTypeAggregated  ClaimType = "AGGREGATED"
	ClaimTypeDistributed ClaimType = "DISTRIBUTED"
)

func (e ClaimType) ToPointer() *ClaimType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ClaimType) IsExact() bool {
	if e != nil {
		switch *e {
		case "NORMAL", "AGGREGATED", "DISTRIBUTED":
			return true
		}
	}
	return false
}
