// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

type ClientExtensionRequestableScopesUpdateResponse struct {
	RequestableScopes []string `json:"requestableScopes,omitzero"`
}

func (c ClientExtensionRequestableScopesUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientExtensionRequestableScopesUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientExtensionRequestableScopesUpdateResponse) GetRequestableScopes() []string {
	if c == nil {
		return nil
	}
	return c.RequestableScopes
}
