// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ClientType - The client type, either `CONFIDENTIAL` or `PUBLIC`. See [RFC 6749, 2.1. Client Types](https://datatracker.ietf.org/doc/html/rfc6749#section-2.1)
// for details.
type ClientType string

const (
	ClientTypePublic       ClientType = "PUBLIC"
	ClientTypeConfidential ClientType = "CONFIDENTIAL"
)

func (e ClientType) ToPointer() *ClientType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ClientType) IsExact() bool {
	if e != nil {
		switch *e {
		case "PUBLIC", "CONFIDENTIAL":
			return true
		}
	}
	return false
}
