// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ClientRegistrationType - Values for the `client_registration_types` RP metadata and the
//
//	`client_registration_types_supported` OP metadata that are defined in
//	[OpenID Connect Federation 1.0](https://openid.net/specs/openid-connect-federation-1_0.html).
type ClientRegistrationType string

const (
	ClientRegistrationTypeAutomatic ClientRegistrationType = "AUTOMATIC"
	ClientRegistrationTypeExplicit  ClientRegistrationType = "EXPLICIT"
)

func (e ClientRegistrationType) ToPointer() *ClientRegistrationType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ClientRegistrationType) IsExact() bool {
	if e != nil {
		switch *e {
		case "AUTOMATIC", "EXPLICIT":
			return true
		}
	}
	return false
}
