// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
	"github.com/authlete/authlete-go-sdk/optionalnullable"
)

type ClientExtensionRequestableScopesGetResponse struct {
	// The requestable scopes for this client. This is null if the Requestable Scopes per Client feature is not enabled for this client.
	//
	RequestableScopes optionalnullable.OptionalNullable[[]string] `json:"requestableScopes,omitzero"`
}

func (c ClientExtensionRequestableScopesGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientExtensionRequestableScopesGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientExtensionRequestableScopesGetResponse) GetRequestableScopes() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.RequestableScopes
}
