// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeliveryMode string

const (
	DeliveryModePing DeliveryMode = "PING"
	DeliveryModePoll DeliveryMode = "POLL"
	DeliveryModePush DeliveryMode = "PUSH"
)

func (e DeliveryMode) ToPointer() *DeliveryMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DeliveryMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "PING", "POLL", "PUSH":
			return true
		}
	}
	return false
}
