// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DeviceCompleteResponseAction - The next action that the authorization server implementation should take.
type DeviceCompleteResponseAction string

const (
	DeviceCompleteResponseActionServerError      DeviceCompleteResponseAction = "SERVER_ERROR"
	DeviceCompleteResponseActionUserCodeNotExist DeviceCompleteResponseAction = "USER_CODE_NOT_EXIST"
	DeviceCompleteResponseActionUserCodeExpired  DeviceCompleteResponseAction = "USER_CODE_EXPIRED"
	DeviceCompleteResponseActionInvalidRequest   DeviceCompleteResponseAction = "INVALID_REQUEST"
	DeviceCompleteResponseActionSuccess          DeviceCompleteResponseAction = "SUCCESS"
)

func (e DeviceCompleteResponseAction) ToPointer() *DeviceCompleteResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DeviceCompleteResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "SERVER_ERROR", "USER_CODE_NOT_EXIST", "USER_CODE_EXPIRED", "INVALID_REQUEST", "SUCCESS":
			return true
		}
	}
	return false
}

type DeviceCompleteResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	//
	Action *DeviceCompleteResponseAction `json:"action,omitzero"`
}

func (d *DeviceCompleteResponse) GetResultCode() *string {
	if d == nil {
		return nil
	}
	return d.ResultCode
}

func (d *DeviceCompleteResponse) GetResultMessage() *string {
	if d == nil {
		return nil
	}
	return d.ResultMessage
}

func (d *DeviceCompleteResponse) GetAction() *DeviceCompleteResponseAction {
	if d == nil {
		return nil
	}
	return d.Action
}
