// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FapiMode string

const (
	FapiModeFapi1Advanced                       FapiMode = "FAPI1_ADVANCED"
	FapiModeFapi1Baseline                       FapiMode = "FAPI1_BASELINE"
	FapiModeFapi2MessageSigningAuthReq          FapiMode = "FAPI2_MESSAGE_SIGNING_AUTH_REQ"
	FapiModeFapi2MessageSigningAuthRes          FapiMode = "FAPI2_MESSAGE_SIGNING_AUTH_RES"
	FapiModeFapi2MessageSigningIntrospectionRes FapiMode = "FAPI2_MESSAGE_SIGNING_INTROSPECTION_RES"
	FapiModeFapi2Security                       FapiMode = "FAPI2_SECURITY"
)

func (e FapiMode) ToPointer() *FapiMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FapiMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "FAPI1_ADVANCED", "FAPI1_BASELINE", "FAPI2_MESSAGE_SIGNING_AUTH_REQ", "FAPI2_MESSAGE_SIGNING_AUTH_RES", "FAPI2_MESSAGE_SIGNING_INTROSPECTION_RES", "FAPI2_SECURITY":
			return true
		}
	}
	return false
}
