// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FederationConfigurationResponseAction - The next action that the authorization server implementation should take.
type FederationConfigurationResponseAction string

const (
	FederationConfigurationResponseActionOk                  FederationConfigurationResponseAction = "OK"
	FederationConfigurationResponseActionNotFound            FederationConfigurationResponseAction = "NOT_FOUND"
	FederationConfigurationResponseActionInternalServerError FederationConfigurationResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e FederationConfigurationResponseAction) ToPointer() *FederationConfigurationResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FederationConfigurationResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "NOT_FOUND", "INTERNAL_SERVER_ERROR":
			return true
		}
	}
	return false
}

type FederationConfigurationResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *FederationConfigurationResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation is to return to the client application.
	// Its format varies depending on the value of `action` parameter.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (f *FederationConfigurationResponse) GetResultCode() *string {
	if f == nil {
		return nil
	}
	return f.ResultCode
}

func (f *FederationConfigurationResponse) GetResultMessage() *string {
	if f == nil {
		return nil
	}
	return f.ResultMessage
}

func (f *FederationConfigurationResponse) GetAction() *FederationConfigurationResponseAction {
	if f == nil {
		return nil
	}
	return f.Action
}

func (f *FederationConfigurationResponse) GetResponseContent() *string {
	if f == nil {
		return nil
	}
	return f.ResponseContent
}
