// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

// FederationRegistrationResponseAction - The next action that the authorization server implementation should take.
type FederationRegistrationResponseAction string

const (
	FederationRegistrationResponseActionOk                  FederationRegistrationResponseAction = "OK"
	FederationRegistrationResponseActionBadRequest          FederationRegistrationResponseAction = "BAD_REQUEST"
	FederationRegistrationResponseActionNotFound            FederationRegistrationResponseAction = "NOT_FOUND"
	FederationRegistrationResponseActionInternalServerError FederationRegistrationResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e FederationRegistrationResponseAction) ToPointer() *FederationRegistrationResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FederationRegistrationResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "BAD_REQUEST", "NOT_FOUND", "INTERNAL_SERVER_ERROR":
			return true
		}
	}
	return false
}

type FederationRegistrationResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *FederationRegistrationResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation can use as the value of `WWW-Authenticate`
	// header on errors.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
	Client          *Client `json:"client,omitzero"`
}

func (f FederationRegistrationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FederationRegistrationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FederationRegistrationResponse) GetResultCode() *string {
	if f == nil {
		return nil
	}
	return f.ResultCode
}

func (f *FederationRegistrationResponse) GetResultMessage() *string {
	if f == nil {
		return nil
	}
	return f.ResultMessage
}

func (f *FederationRegistrationResponse) GetAction() *FederationRegistrationResponseAction {
	if f == nil {
		return nil
	}
	return f.Action
}

func (f *FederationRegistrationResponse) GetResponseContent() *string {
	if f == nil {
		return nil
	}
	return f.ResponseContent
}

func (f *FederationRegistrationResponse) GetClient() *Client {
	if f == nil {
		return nil
	}
	return f.Client
}
