// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GMResponseAction - The next action that the authorization server implementation should take.
type GMResponseAction string

const (
	GMResponseActionOk            GMResponseAction = "OK"
	GMResponseActionNoContent     GMResponseAction = "NO_CONTENT"
	GMResponseActionUnauthorized  GMResponseAction = "UNAUTHORIZED"
	GMResponseActionForbidden     GMResponseAction = "FORBIDDEN"
	GMResponseActionNotFound      GMResponseAction = "NOT_FOUND"
	GMResponseActionCallerError   GMResponseAction = "CALLER_ERROR"
	GMResponseActionAuthleteError GMResponseAction = "AUTHLETE_ERROR"
)

func (e GMResponseAction) ToPointer() *GMResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GMResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "NO_CONTENT", "UNAUTHORIZED", "FORBIDDEN", "NOT_FOUND", "CALLER_ERROR", "AUTHLETE_ERROR":
			return true
		}
	}
	return false
}

type GMResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *GMResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation is to return to the client application.
	// Its format varies depending on the value of `action` parameter.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
	// Get the expected nonce value for DPoP proof JWT, which should be used
	// as the value of the `DPoP-Nonce` HTTP header.
	//
	DpopNonce *string `json:"dpopNonce,omitzero"`
}

func (g *GMResponse) GetResultCode() *string {
	if g == nil {
		return nil
	}
	return g.ResultCode
}

func (g *GMResponse) GetResultMessage() *string {
	if g == nil {
		return nil
	}
	return g.ResultMessage
}

func (g *GMResponse) GetAction() *GMResponseAction {
	if g == nil {
		return nil
	}
	return g.Action
}

func (g *GMResponse) GetResponseContent() *string {
	if g == nil {
		return nil
	}
	return g.ResponseContent
}

func (g *GMResponse) GetDpopNonce() *string {
	if g == nil {
		return nil
	}
	return g.DpopNonce
}
