// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GrantType - The grant type of the access token when the access token was created.
type GrantType string

const (
	GrantTypeAuthorizationCode GrantType = "AUTHORIZATION_CODE"
	GrantTypeImplicit          GrantType = "IMPLICIT"
	GrantTypePassword          GrantType = "PASSWORD"
	GrantTypeClientCredentials GrantType = "CLIENT_CREDENTIALS"
	GrantTypeRefreshToken      GrantType = "REFRESH_TOKEN"
	GrantTypeCiba              GrantType = "CIBA"
	GrantTypeDeviceCode        GrantType = "DEVICE_CODE"
	GrantTypeTokenExchange     GrantType = "TOKEN_EXCHANGE"
	GrantTypeJwtBearer         GrantType = "JWT_BEARER"
	GrantTypePreAuthorizedCode GrantType = "PRE_AUTHORIZED_CODE"
)

func (e GrantType) ToPointer() *GrantType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GrantType) IsExact() bool {
	if e != nil {
		switch *e {
		case "AUTHORIZATION_CODE", "IMPLICIT", "PASSWORD", "CLIENT_CREDENTIALS", "REFRESH_TOKEN", "CIBA", "DEVICE_CODE", "TOKEN_EXCHANGE", "JWT_BEARER", "PRE_AUTHORIZED_CODE":
			return true
		}
	}
	return false
}
