// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GrantManagementAction - The grant management action of the device authorization request.
//
// The `grant_management_action` request parameter is defined in
// [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
type GrantManagementAction string

const (
	GrantManagementActionCreate  GrantManagementAction = "CREATE"
	GrantManagementActionQuery   GrantManagementAction = "QUERY"
	GrantManagementActionReplace GrantManagementAction = "REPLACE"
	GrantManagementActionRevoke  GrantManagementAction = "REVOKE"
	GrantManagementActionMerge   GrantManagementAction = "MERGE"
)

func (e GrantManagementAction) ToPointer() *GrantManagementAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GrantManagementAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "CREATE", "QUERY", "REPLACE", "REVOKE", "MERGE":
			return true
		}
	}
	return false
}
