// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

// HskCreateResponseAction - Result of the API call.
type HskCreateResponseAction string

const (
	HskCreateResponseActionSuccess        HskCreateResponseAction = "SUCCESS"
	HskCreateResponseActionInvalidRequest HskCreateResponseAction = "INVALID_REQUEST"
	HskCreateResponseActionNotFound       HskCreateResponseAction = "NOT_FOUND"
	HskCreateResponseActionServerError    HskCreateResponseAction = "SERVER_ERROR"
)

func (e HskCreateResponseAction) ToPointer() *HskCreateResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *HskCreateResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "SUCCESS", "INVALID_REQUEST", "NOT_FOUND", "SERVER_ERROR":
			return true
		}
	}
	return false
}

type HskCreateResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// Result of the API call.
	Action *HskCreateResponseAction `json:"action,omitzero"`
	// Holds information about a key managed in an HSM (Hardware Security Module)
	//
	Hsk *Hsk `json:"hsk,omitzero"`
}

func (h HskCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HskCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HskCreateResponse) GetResultCode() *string {
	if h == nil {
		return nil
	}
	return h.ResultCode
}

func (h *HskCreateResponse) GetResultMessage() *string {
	if h == nil {
		return nil
	}
	return h.ResultMessage
}

func (h *HskCreateResponse) GetAction() *HskCreateResponseAction {
	if h == nil {
		return nil
	}
	return h.Action
}

func (h *HskCreateResponse) GetHsk() *Hsk {
	if h == nil {
		return nil
	}
	return h.Hsk
}
