// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

// HskDeleteResponseAction - Result of the API call
type HskDeleteResponseAction string

const (
	HskDeleteResponseActionSuccess        HskDeleteResponseAction = "SUCCESS"
	HskDeleteResponseActionInvalidRequest HskDeleteResponseAction = "INVALID_REQUEST"
	HskDeleteResponseActionNotFound       HskDeleteResponseAction = "NOT_FOUND"
	HskDeleteResponseActionServerError    HskDeleteResponseAction = "SERVER_ERROR"
)

func (e HskDeleteResponseAction) ToPointer() *HskDeleteResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *HskDeleteResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "SUCCESS", "INVALID_REQUEST", "NOT_FOUND", "SERVER_ERROR":
			return true
		}
	}
	return false
}

type HskDeleteResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// Result of the API call
	Action *HskDeleteResponseAction `json:"action,omitzero"`
	// Holds information about a key managed in an HSM (Hardware Security Module)
	//
	Hsk *Hsk `json:"hsk,omitzero"`
}

func (h HskDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HskDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HskDeleteResponse) GetResultCode() *string {
	if h == nil {
		return nil
	}
	return h.ResultCode
}

func (h *HskDeleteResponse) GetResultMessage() *string {
	if h == nil {
		return nil
	}
	return h.ResultMessage
}

func (h *HskDeleteResponse) GetAction() *HskDeleteResponseAction {
	if h == nil {
		return nil
	}
	return h.Action
}

func (h *HskDeleteResponse) GetHsk() *Hsk {
	if h == nil {
		return nil
	}
	return h.Hsk
}
