// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

// HskGetListResponseAction - Result of the API call
type HskGetListResponseAction string

const (
	HskGetListResponseActionSuccess        HskGetListResponseAction = "SUCCESS"
	HskGetListResponseActionInvalidRequest HskGetListResponseAction = "INVALID_REQUEST"
	HskGetListResponseActionServerError    HskGetListResponseAction = "SERVER_ERROR"
)

func (e HskGetListResponseAction) ToPointer() *HskGetListResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *HskGetListResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "SUCCESS", "INVALID_REQUEST", "SERVER_ERROR":
			return true
		}
	}
	return false
}

type HskGetListResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// Result of the API call
	Action *HskGetListResponseAction `json:"action,omitzero"`
	// List of HSK
	Hsks []Hsk `json:"hsks,omitzero"`
}

func (h HskGetListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HskGetListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HskGetListResponse) GetResultCode() *string {
	if h == nil {
		return nil
	}
	return h.ResultCode
}

func (h *HskGetListResponse) GetResultMessage() *string {
	if h == nil {
		return nil
	}
	return h.ResultMessage
}

func (h *HskGetListResponse) GetAction() *HskGetListResponseAction {
	if h == nil {
		return nil
	}
	return h.Action
}

func (h *HskGetListResponse) GetHsks() []Hsk {
	if h == nil {
		return nil
	}
	return h.Hsks
}
