// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IdtokenReissueResponseAction - The next action that the implementation of the token endpoint should take.
type IdtokenReissueResponseAction string

const (
	IdtokenReissueResponseActionOk                  IdtokenReissueResponseAction = "OK"
	IdtokenReissueResponseActionInternalServerError IdtokenReissueResponseAction = "INTERNAL_SERVER_ERROR"
	IdtokenReissueResponseActionCallerError         IdtokenReissueResponseAction = "CALLER_ERROR"
)

func (e IdtokenReissueResponseAction) ToPointer() *IdtokenReissueResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *IdtokenReissueResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "INTERNAL_SERVER_ERROR", "CALLER_ERROR":
			return true
		}
	}
	return false
}

type IdtokenReissueResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the implementation of the token endpoint should take.
	Action *IdtokenReissueResponseAction `json:"action,omitzero"`
	// The response content that can be used as the message body of the token response that should
	// be returned from the token endpoint.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
	// The reissued ID token
	//
	IDToken *string `json:"idToken,omitzero"`
}

func (i *IdtokenReissueResponse) GetResultCode() *string {
	if i == nil {
		return nil
	}
	return i.ResultCode
}

func (i *IdtokenReissueResponse) GetResultMessage() *string {
	if i == nil {
		return nil
	}
	return i.ResultMessage
}

func (i *IdtokenReissueResponse) GetAction() *IdtokenReissueResponseAction {
	if i == nil {
		return nil
	}
	return i.Action
}

func (i *IdtokenReissueResponse) GetResponseContent() *string {
	if i == nil {
		return nil
	}
	return i.ResponseContent
}

func (i *IdtokenReissueResponse) GetIDToken() *string {
	if i == nil {
		return nil
	}
	return i.IDToken
}
