// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JweAlg - this is the 'alg' header value for encrypted JWT tokens.
// Depending upon the context, this refers to key transport scheme to be used by the client and by the server. For instance:
// - as `authorizationEncryptionAlg` value, it refers to the encoding algorithm used by server for transporting they keys on JARM objects
// - as `requestEncryptionAlg` value, it refers to the expected key transport encoding algorithm that server expect from client when encrypting a Request Object
// - as `idTokenEncryptionAlg` value, it refers to the algorithm used by the server to key transport of id_tokens
//
// **Please note that some of the algorithms are more secure than others, some are not supported very well cross platforms and some (like RSA1_5) is known to be weak**.
type JweAlg string

const (
	JweAlgRsa15            JweAlg = "RSA1_5"
	JweAlgRsaOaep          JweAlg = "RSA_OAEP"
	JweAlgRsaOaep256       JweAlg = "RSA_OAEP_256"
	JweAlgA128Kw           JweAlg = "A128KW"
	JweAlgA192Kw           JweAlg = "A192KW"
	JweAlgA256Kw           JweAlg = "A256KW"
	JweAlgDir              JweAlg = "DIR"
	JweAlgEcdhEs           JweAlg = "ECDH_ES"
	JweAlgEcdhEsA128Kw     JweAlg = "ECDH_ES_A128KW"
	JweAlgEcdhEsA192Kw     JweAlg = "ECDH_ES_A192KW"
	JweAlgEcdhEsA256Kw     JweAlg = "ECDH_ES_A256KW"
	JweAlgA128Gcmkw        JweAlg = "A128GCMKW"
	JweAlgA192Gcmkw        JweAlg = "A192GCMKW"
	JweAlgA256Gcmkw        JweAlg = "A256GCMKW"
	JweAlgPbes2Hs256A128Kw JweAlg = "PBES2_HS256_A128KW"
	JweAlgPbes2Hs384A192Kw JweAlg = "PBES2_HS384_A192KW"
	JweAlgPbes2Hs512A256Kw JweAlg = "PBES2_HS512_A256KW"
)

func (e JweAlg) ToPointer() *JweAlg {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *JweAlg) IsExact() bool {
	if e != nil {
		switch *e {
		case "RSA1_5", "RSA_OAEP", "RSA_OAEP_256", "A128KW", "A192KW", "A256KW", "DIR", "ECDH_ES", "ECDH_ES_A128KW", "ECDH_ES_A192KW", "ECDH_ES_A256KW", "A128GCMKW", "A192GCMKW", "A256GCMKW", "PBES2_HS256_A128KW", "PBES2_HS384_A192KW", "PBES2_HS512_A256KW":
			return true
		}
	}
	return false
}
