// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// NativeSsoLogoutResponseAction - The next action that the API caller should take.
type NativeSsoLogoutResponseAction string

const (
	NativeSsoLogoutResponseActionOk          NativeSsoLogoutResponseAction = "OK"
	NativeSsoLogoutResponseActionServerError NativeSsoLogoutResponseAction = "SERVER_ERROR"
	NativeSsoLogoutResponseActionCallerError NativeSsoLogoutResponseAction = "CALLER_ERROR"
)

func (e NativeSsoLogoutResponseAction) ToPointer() *NativeSsoLogoutResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NativeSsoLogoutResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "SERVER_ERROR", "CALLER_ERROR":
			return true
		}
	}
	return false
}

type NativeSsoLogoutResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the API caller should take.
	//
	Action *NativeSsoLogoutResponseAction `json:"action,omitzero"`
	// The number of deleted access/refresh token records.
	//
	Count *int64 `json:"count,omitzero"`
}

func (n *NativeSsoLogoutResponse) GetResultCode() *string {
	if n == nil {
		return nil
	}
	return n.ResultCode
}

func (n *NativeSsoLogoutResponse) GetResultMessage() *string {
	if n == nil {
		return nil
	}
	return n.ResultMessage
}

func (n *NativeSsoLogoutResponse) GetAction() *NativeSsoLogoutResponseAction {
	if n == nil {
		return nil
	}
	return n.Action
}

func (n *NativeSsoLogoutResponse) GetCount() *int64 {
	if n == nil {
		return nil
	}
	return n.Count
}
