// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// NativeSsoResponseAction - The next action that the implementation of the token endpoint should take.
type NativeSsoResponseAction string

const (
	NativeSsoResponseActionOk                  NativeSsoResponseAction = "OK"
	NativeSsoResponseActionInternalServerError NativeSsoResponseAction = "INTERNAL_SERVER_ERROR"
	NativeSsoResponseActionCallerError         NativeSsoResponseAction = "CALLER_ERROR"
)

func (e NativeSsoResponseAction) ToPointer() *NativeSsoResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NativeSsoResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "INTERNAL_SERVER_ERROR", "CALLER_ERROR":
			return true
		}
	}
	return false
}

type NativeSsoResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the implementation of the token endpoint should take.
	//
	Action *NativeSsoResponseAction `json:"action,omitzero"`
	// The response content that can be used as the message body of the token response that should be
	// returned from the token endpoint.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
	// The issued ID token.
	//
	IDToken *string `json:"idToken,omitzero"`
}

func (n *NativeSsoResponse) GetResultCode() *string {
	if n == nil {
		return nil
	}
	return n.ResultCode
}

func (n *NativeSsoResponse) GetResultMessage() *string {
	if n == nil {
		return nil
	}
	return n.ResultMessage
}

func (n *NativeSsoResponse) GetAction() *NativeSsoResponseAction {
	if n == nil {
		return nil
	}
	return n.Action
}

func (n *NativeSsoResponse) GetResponseContent() *string {
	if n == nil {
		return nil
	}
	return n.ResponseContent
}

func (n *NativeSsoResponse) GetIDToken() *string {
	if n == nil {
		return nil
	}
	return n.IDToken
}
