// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Prompt - The prompt that the UI displayed to the end-user must satisfy as the minimum level. This value comes from `prompt` request parameter.
//
// When the authorization request does not contain `prompt` request parameter, `CONSENT` is used as the default value.
//
// See "[OpenID Connect Core 1.0, 3.1.2.1. Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), prompt" for `prompt` request parameter.
type Prompt string

const (
	PromptNone          Prompt = "NONE"
	PromptLogin         Prompt = "LOGIN"
	PromptConsent       Prompt = "CONSENT"
	PromptSelectAccount Prompt = "SELECT_ACCOUNT"
	PromptCreate        Prompt = "CREATE"
)

func (e Prompt) ToPointer() *Prompt {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Prompt) IsExact() bool {
	if e != nil {
		switch *e {
		case "NONE", "LOGIN", "CONSENT", "SELECT_ACCOUNT", "CREATE":
			return true
		}
	}
	return false
}
