// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponseType string

const (
	ResponseTypeNone             ResponseType = "NONE"
	ResponseTypeCode             ResponseType = "CODE"
	ResponseTypeToken            ResponseType = "TOKEN"
	ResponseTypeIDToken          ResponseType = "ID_TOKEN"
	ResponseTypeCodeToken        ResponseType = "CODE_TOKEN"
	ResponseTypeCodeIDToken      ResponseType = "CODE_ID_TOKEN"
	ResponseTypeIDTokenToken     ResponseType = "ID_TOKEN_TOKEN"
	ResponseTypeCodeIDTokenToken ResponseType = "CODE_ID_TOKEN_TOKEN"
)

func (e ResponseType) ToPointer() *ResponseType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ResponseType) IsExact() bool {
	if e != nil {
		switch *e {
		case "NONE", "CODE", "TOKEN", "ID_TOKEN", "CODE_TOKEN", "CODE_ID_TOKEN", "ID_TOKEN_TOKEN", "CODE_ID_TOKEN_TOKEN":
			return true
		}
	}
	return false
}
