// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ServiceProfile string

const (
	ServiceProfileFapi        ServiceProfile = "FAPI"
	ServiceProfileOpenBanking ServiceProfile = "OPEN_BANKING"
)

func (e ServiceProfile) ToPointer() *ServiceProfile {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ServiceProfile) IsExact() bool {
	if e != nil {
		switch *e {
		case "FAPI", "OPEN_BANKING":
			return true
		}
	}
	return false
}
