// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

type ServiceJwksGetResponse struct {
	// An array of [JWK](https://datatracker.ietf.org/doc/html/rfc7517)s.
	Keys []map[string]any `json:"keys,omitzero"`
}

func (s ServiceJwksGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServiceJwksGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServiceJwksGetResponse) GetKeys() []map[string]any {
	if s == nil {
		return nil
	}
	return s.Keys
}
