// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// StandardIntrospectionResponseAction - The next action that the authorization server implementation should take.
type StandardIntrospectionResponseAction string

const (
	StandardIntrospectionResponseActionInternalServerError StandardIntrospectionResponseAction = "INTERNAL_SERVER_ERROR"
	StandardIntrospectionResponseActionBadRequest          StandardIntrospectionResponseAction = "BAD_REQUEST"
	StandardIntrospectionResponseActionOk                  StandardIntrospectionResponseAction = "OK"
	StandardIntrospectionResponseActionJwt                 StandardIntrospectionResponseAction = "JWT"
)

func (e StandardIntrospectionResponseAction) ToPointer() *StandardIntrospectionResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StandardIntrospectionResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "INTERNAL_SERVER_ERROR", "BAD_REQUEST", "OK", "JWT":
			return true
		}
	}
	return false
}

type StandardIntrospectionResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *StandardIntrospectionResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation is to return to the client
	// application.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (s *StandardIntrospectionResponse) GetResultCode() *string {
	if s == nil {
		return nil
	}
	return s.ResultCode
}

func (s *StandardIntrospectionResponse) GetResultMessage() *string {
	if s == nil {
		return nil
	}
	return s.ResultMessage
}

func (s *StandardIntrospectionResponse) GetAction() *StandardIntrospectionResponseAction {
	if s == nil {
		return nil
	}
	return s.Action
}

func (s *StandardIntrospectionResponse) GetResponseContent() *string {
	if s == nil {
		return nil
	}
	return s.ResponseContent
}
