// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SubjectType - The subject type that the client application requests. Details about the subject type are described in
// [OpenID Connect Core 1.0, 8. Subjct Identifier Types](https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes).
//
// This property corresponds to `subject_type` in
// [OpenID Connect Dynamic Client Registration 1.0, 2. Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).
type SubjectType string

const (
	SubjectTypePublic   SubjectType = "PUBLIC"
	SubjectTypePairwise SubjectType = "PAIRWISE"
)

func (e SubjectType) ToPointer() *SubjectType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SubjectType) IsExact() bool {
	if e != nil {
		switch *e {
		case "PUBLIC", "PAIRWISE":
			return true
		}
	}
	return false
}
