// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TokenFailResponseAction - The next action that the authorization server implementation should take.
type TokenFailResponseAction string

const (
	TokenFailResponseActionInternalServerError TokenFailResponseAction = "INTERNAL_SERVER_ERROR"
	TokenFailResponseActionBadRequest          TokenFailResponseAction = "BAD_REQUEST"
)

func (e TokenFailResponseAction) ToPointer() *TokenFailResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TokenFailResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "INTERNAL_SERVER_ERROR", "BAD_REQUEST":
			return true
		}
	}
	return false
}

type TokenFailResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *TokenFailResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation is to return to the client application.
	// Its format varies depending on the value of `action` parameter. See description for details.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (t *TokenFailResponse) GetResultCode() *string {
	if t == nil {
		return nil
	}
	return t.ResultCode
}

func (t *TokenFailResponse) GetResultMessage() *string {
	if t == nil {
		return nil
	}
	return t.ResultMessage
}

func (t *TokenFailResponse) GetAction() *TokenFailResponseAction {
	if t == nil {
		return nil
	}
	return t.Action
}

func (t *TokenFailResponse) GetResponseContent() *string {
	if t == nil {
		return nil
	}
	return t.ResponseContent
}
