// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TokenType - The token type identifier used in OAuth 2.0 Token Exchange (RFC 8693).
// The API returns short codes (enum constant names) in response fields.
type TokenType string

const (
	TokenTypeJwt           TokenType = "JWT"
	TokenTypeAccessToken   TokenType = "ACCESS_TOKEN"
	TokenTypeRefreshToken  TokenType = "REFRESH_TOKEN"
	TokenTypeIDToken       TokenType = "ID_TOKEN"
	TokenTypeSaml1         TokenType = "SAML1"
	TokenTypeSaml2         TokenType = "SAML2"
	TokenTypeDeviceSecret  TokenType = "DEVICE_SECRET"
	TokenTypeDeviceCode    TokenType = "DEVICE_CODE"
	TokenTypeTokenExchange TokenType = "TOKEN_EXCHANGE"
	TokenTypeJwtBearer     TokenType = "JWT_BEARER"
)

func (e TokenType) ToPointer() *TokenType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TokenType) IsExact() bool {
	if e != nil {
		switch *e {
		case "JWT", "ACCESS_TOKEN", "REFRESH_TOKEN", "ID_TOKEN", "SAML1", "SAML2", "DEVICE_SECRET", "DEVICE_CODE", "TOKEN_EXCHANGE", "JWT_BEARER":
			return true
		}
	}
	return false
}
