// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TokenRevokeResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The number of tokens revoked
	Count *int64 `json:"count,omitzero"`
}

func (t *TokenRevokeResponse) GetResultCode() *string {
	if t == nil {
		return nil
	}
	return t.ResultCode
}

func (t *TokenRevokeResponse) GetResultMessage() *string {
	if t == nil {
		return nil
	}
	return t.ResultMessage
}

func (t *TokenRevokeResponse) GetCount() *int64 {
	if t == nil {
		return nil
	}
	return t.Count
}
