// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

// TokenUpdateResponseAction - The next action that the authorization server implementation should take.
type TokenUpdateResponseAction string

const (
	TokenUpdateResponseActionInternalServerError TokenUpdateResponseAction = "INTERNAL_SERVER_ERROR"
	TokenUpdateResponseActionBadRequest          TokenUpdateResponseAction = "BAD_REQUEST"
	TokenUpdateResponseActionForbidden           TokenUpdateResponseAction = "FORBIDDEN"
	TokenUpdateResponseActionNotFound            TokenUpdateResponseAction = "NOT_FOUND"
	TokenUpdateResponseActionOk                  TokenUpdateResponseAction = "OK"
)

func (e TokenUpdateResponseAction) ToPointer() *TokenUpdateResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TokenUpdateResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "INTERNAL_SERVER_ERROR", "BAD_REQUEST", "FORBIDDEN", "NOT_FOUND", "OK":
			return true
		}
	}
	return false
}

type TokenUpdateResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *TokenUpdateResponseAction `json:"action,omitzero"`
	// The access token which has been specified by the request.
	AccessToken *string `json:"accessToken,omitzero"`
	// The date at which the access token will expire.
	//
	AccessTokenExpiresAt *int64 `json:"accessTokenExpiresAt,omitzero"`
	// The extra properties associated with the access token.
	//
	Properties []Property `json:"properties,omitzero"`
	// The scopes associated with the access token.
	//
	Scopes []string `json:"scopes,omitzero"`
	// The authorization details. This represents the value of the `authorization_details`
	// request parameter in the preceding device authorization request which is defined in
	// "OAuth 2.0 Rich Authorization Requests".
	//
	AuthorizationDetails *AuthzDetails `json:"authorizationDetails,omitzero"`
	// The token type associated with the access token.
	//
	TokenType *string `json:"tokenType,omitzero"`
	// the flag which indicates whether the access token is for an external
	// attachment.
	//
	ForExternalAttachment *bool `json:"forExternalAttachment,omitzero"`
	// Set the unique token identifier.
	//
	TokenID *string `json:"tokenId,omitzero"`
	// The datetime at which the newly issued refresh token will expire.
	// The value is represented in milliseconds since the Unix epoch (1970-01-01).
	//
	RefreshTokenExpiresAt *int64 `json:"refreshTokenExpiresAt,omitzero"`
}

func (t TokenUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TokenUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TokenUpdateResponse) GetResultCode() *string {
	if t == nil {
		return nil
	}
	return t.ResultCode
}

func (t *TokenUpdateResponse) GetResultMessage() *string {
	if t == nil {
		return nil
	}
	return t.ResultMessage
}

func (t *TokenUpdateResponse) GetAction() *TokenUpdateResponseAction {
	if t == nil {
		return nil
	}
	return t.Action
}

func (t *TokenUpdateResponse) GetAccessToken() *string {
	if t == nil {
		return nil
	}
	return t.AccessToken
}

func (t *TokenUpdateResponse) GetAccessTokenExpiresAt() *int64 {
	if t == nil {
		return nil
	}
	return t.AccessTokenExpiresAt
}

func (t *TokenUpdateResponse) GetProperties() []Property {
	if t == nil {
		return nil
	}
	return t.Properties
}

func (t *TokenUpdateResponse) GetScopes() []string {
	if t == nil {
		return nil
	}
	return t.Scopes
}

func (t *TokenUpdateResponse) GetAuthorizationDetails() *AuthzDetails {
	if t == nil {
		return nil
	}
	return t.AuthorizationDetails
}

func (t *TokenUpdateResponse) GetTokenType() *string {
	if t == nil {
		return nil
	}
	return t.TokenType
}

func (t *TokenUpdateResponse) GetForExternalAttachment() *bool {
	if t == nil {
		return nil
	}
	return t.ForExternalAttachment
}

func (t *TokenUpdateResponse) GetTokenID() *string {
	if t == nil {
		return nil
	}
	return t.TokenID
}

func (t *TokenUpdateResponse) GetRefreshTokenExpiresAt() *int64 {
	if t == nil {
		return nil
	}
	return t.RefreshTokenExpiresAt
}
