// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TokenRevokeRequest struct {
	// The identifier of an access token to revoke
	//
	// The hash of an access token is recognized as an identifier as well as the access token itself.
	//
	AccessTokenIdentifier *string `json:"accessTokenIdentifier,omitzero" form:"name=accessTokenIdentifier"`
	// The identifier of a refresh token to revoke.
	//
	// The hash of a refresh token is recognized as an identifier as well as the refresh token itself.
	//
	RefreshTokenIdentifier *string `json:"refreshTokenIdentifier,omitzero" form:"name=refreshTokenIdentifier"`
	// The client ID of the access token to be revoked.
	//
	// Both the numeric client ID and the alias are recognized as an identifier
	// of a client.
	//
	ClientIdentifier *string `json:"clientIdentifier,omitzero" form:"name=clientIdentifier"`
	// The subject of a resource owner.
	//
	Subject *string `json:"subject,omitzero" form:"name=subject"`
}

func (t *TokenRevokeRequest) GetAccessTokenIdentifier() *string {
	if t == nil {
		return nil
	}
	return t.AccessTokenIdentifier
}

func (t *TokenRevokeRequest) GetRefreshTokenIdentifier() *string {
	if t == nil {
		return nil
	}
	return t.RefreshTokenIdentifier
}

func (t *TokenRevokeRequest) GetClientIdentifier() *string {
	if t == nil {
		return nil
	}
	return t.ClientIdentifier
}

func (t *TokenRevokeRequest) GetSubject() *string {
	if t == nil {
		return nil
	}
	return t.Subject
}
