// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UserCodeCharset - The character set for end-user verification codes (`user_code`) for Device Flow.
type UserCodeCharset string

const (
	UserCodeCharsetBase20  UserCodeCharset = "BASE20"
	UserCodeCharsetNumeric UserCodeCharset = "NUMERIC"
)

func (e UserCodeCharset) ToPointer() *UserCodeCharset {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UserCodeCharset) IsExact() bool {
	if e != nil {
		switch *e {
		case "BASE20", "NUMERIC":
			return true
		}
	}
	return false
}
