// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UserinfoIssueResponseAction - The next action that the authorization server implementation should take.
type UserinfoIssueResponseAction string

const (
	UserinfoIssueResponseActionInternalServerError UserinfoIssueResponseAction = "INTERNAL_SERVER_ERROR"
	UserinfoIssueResponseActionBadRequest          UserinfoIssueResponseAction = "BAD_REQUEST"
	UserinfoIssueResponseActionUnauthorized        UserinfoIssueResponseAction = "UNAUTHORIZED"
	UserinfoIssueResponseActionForbidden           UserinfoIssueResponseAction = "FORBIDDEN"
	UserinfoIssueResponseActionJSON                UserinfoIssueResponseAction = "JSON"
	UserinfoIssueResponseActionJwt                 UserinfoIssueResponseAction = "JWT"
)

func (e UserinfoIssueResponseAction) ToPointer() *UserinfoIssueResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UserinfoIssueResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "INTERNAL_SERVER_ERROR", "BAD_REQUEST", "UNAUTHORIZED", "FORBIDDEN", "JSON", "JWT":
			return true
		}
	}
	return false
}

type UserinfoIssueResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *UserinfoIssueResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation can use as the value of `WWW-Authenticate`
	// header on errors.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
	// The signature header of the response message.
	//
	Signature *string `json:"signature,omitzero"`
	// The signature-input header of the response message
	//
	SignatureInput *string `json:"signatureInput,omitzero"`
	// The content-digest header of the response message
	//
	ContentDigest *string `json:"contentDigest,omitzero"`
}

func (u *UserinfoIssueResponse) GetResultCode() *string {
	if u == nil {
		return nil
	}
	return u.ResultCode
}

func (u *UserinfoIssueResponse) GetResultMessage() *string {
	if u == nil {
		return nil
	}
	return u.ResultMessage
}

func (u *UserinfoIssueResponse) GetAction() *UserinfoIssueResponseAction {
	if u == nil {
		return nil
	}
	return u.Action
}

func (u *UserinfoIssueResponse) GetResponseContent() *string {
	if u == nil {
		return nil
	}
	return u.ResponseContent
}

func (u *UserinfoIssueResponse) GetSignature() *string {
	if u == nil {
		return nil
	}
	return u.Signature
}

func (u *UserinfoIssueResponse) GetSignatureInput() *string {
	if u == nil {
		return nil
	}
	return u.SignatureInput
}

func (u *UserinfoIssueResponse) GetContentDigest() *string {
	if u == nil {
		return nil
	}
	return u.ContentDigest
}
