// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

// VciBatchParseResponseAction - The next action that the batch credential endpoint should take.
type VciBatchParseResponseAction string

const (
	VciBatchParseResponseActionOk                  VciBatchParseResponseAction = "OK"
	VciBatchParseResponseActionBadRequest          VciBatchParseResponseAction = "BAD_REQUEST"
	VciBatchParseResponseActionUnauthorized        VciBatchParseResponseAction = "UNAUTHORIZED"
	VciBatchParseResponseActionForbidden           VciBatchParseResponseAction = "FORBIDDEN"
	VciBatchParseResponseActionInternalServerError VciBatchParseResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e VciBatchParseResponseAction) ToPointer() *VciBatchParseResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VciBatchParseResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "BAD_REQUEST", "UNAUTHORIZED", "FORBIDDEN", "INTERNAL_SERVER_ERROR":
			return true
		}
	}
	return false
}

type VciBatchParseResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the batch credential endpoint should take.
	Action *VciBatchParseResponseAction `json:"action,omitzero"`
	// The content of the response to the request sender.
	ResponseContent *string `json:"responseContent,omitzero"`
	// Information about the credential requests in the batch credential
	// request.
	//
	Info []CredentialRequestInfo `json:"info,omitzero"`
}

func (v VciBatchParseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciBatchParseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciBatchParseResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciBatchParseResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciBatchParseResponse) GetAction() *VciBatchParseResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciBatchParseResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}

func (v *VciBatchParseResponse) GetInfo() []CredentialRequestInfo {
	if v == nil {
		return nil
	}
	return v.Info
}
