// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

type VciBatchIssueRequest struct {
	// The access token that came along with the credential request.
	AccessToken *string `json:"accessToken,omitzero"`
	// The instructions for issuance of credentials and/or transaction IDs.
	Orders []CredentialIssuanceOrder `json:"orders,omitzero"`
}

func (v VciBatchIssueRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciBatchIssueRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciBatchIssueRequest) GetAccessToken() *string {
	if v == nil {
		return nil
	}
	return v.AccessToken
}

func (v *VciBatchIssueRequest) GetOrders() []CredentialIssuanceOrder {
	if v == nil {
		return nil
	}
	return v.Orders
}
