// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VciBatchIssueResponseAction - The next action that the implementation of the batch credential
// endpoint should take.
type VciBatchIssueResponseAction string

const (
	VciBatchIssueResponseActionOk                  VciBatchIssueResponseAction = "OK"
	VciBatchIssueResponseActionUnauthorized        VciBatchIssueResponseAction = "UNAUTHORIZED"
	VciBatchIssueResponseActionForbidden           VciBatchIssueResponseAction = "FORBIDDEN"
	VciBatchIssueResponseActionInternalServerError VciBatchIssueResponseAction = "INTERNAL_SERVER_ERROR"
	VciBatchIssueResponseActionCallerError         VciBatchIssueResponseAction = "CALLER_ERROR"
)

func (e VciBatchIssueResponseAction) ToPointer() *VciBatchIssueResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VciBatchIssueResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "UNAUTHORIZED", "FORBIDDEN", "INTERNAL_SERVER_ERROR", "CALLER_ERROR":
			return true
		}
	}
	return false
}

type VciBatchIssueResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the implementation of the batch credential
	// endpoint should take.
	//
	Action *VciBatchIssueResponseAction `json:"action,omitzero"`
	// The content of the response that the implementation of the batch
	// credential endpoint should return.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (v *VciBatchIssueResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciBatchIssueResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciBatchIssueResponse) GetAction() *VciBatchIssueResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciBatchIssueResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}
