// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VciDeferredIssueResponseAction - The next action that the implementation of the deferred credential
// endpoint should take.
type VciDeferredIssueResponseAction string

const (
	VciDeferredIssueResponseActionOk                  VciDeferredIssueResponseAction = "OK"
	VciDeferredIssueResponseActionForbidden           VciDeferredIssueResponseAction = "FORBIDDEN"
	VciDeferredIssueResponseActionInternalServerError VciDeferredIssueResponseAction = "INTERNAL_SERVER_ERROR"
	VciDeferredIssueResponseActionCallerError         VciDeferredIssueResponseAction = "CALLER_ERROR"
)

func (e VciDeferredIssueResponseAction) ToPointer() *VciDeferredIssueResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VciDeferredIssueResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "FORBIDDEN", "INTERNAL_SERVER_ERROR", "CALLER_ERROR":
			return true
		}
	}
	return false
}

type VciDeferredIssueResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the implementation of the deferred credential
	// endpoint should take.
	//
	Action *VciDeferredIssueResponseAction `json:"action,omitzero"`
	// The content of the response that the implementation of the deferred
	// credential endpoint should return.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (v *VciDeferredIssueResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciDeferredIssueResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciDeferredIssueResponse) GetAction() *VciDeferredIssueResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciDeferredIssueResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}
