// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VciJwtissuerResponseAction - The next action that the implementation of the JWT issuer metadata
// endpoint (`/.well-known/jwt-issuer`) should take after getting
// a response from Authlete's `/vci/jwtissuer` API.
type VciJwtissuerResponseAction string

const (
	VciJwtissuerResponseActionOk                  VciJwtissuerResponseAction = "OK"
	VciJwtissuerResponseActionNotFound            VciJwtissuerResponseAction = "NOT_FOUND"
	VciJwtissuerResponseActionInternalServerError VciJwtissuerResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e VciJwtissuerResponseAction) ToPointer() *VciJwtissuerResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VciJwtissuerResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "NOT_FOUND", "INTERNAL_SERVER_ERROR":
			return true
		}
	}
	return false
}

type VciJwtissuerResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the implementation of the JWT issuer metadata
	// endpoint (`/.well-known/jwt-issuer`) should take after getting
	// a response from Authlete's `/vci/jwtissuer` API.
	//
	Action *VciJwtissuerResponseAction `json:"action,omitzero"`
	// Get the content that the implementation of the credential issuer
	// metadata endpoint should use when it constructs a response.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (v *VciJwtissuerResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciJwtissuerResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciJwtissuerResponse) GetAction() *VciJwtissuerResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciJwtissuerResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}
