// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VciJwksResponseAction - The next action that the implementation of the JWK Set document
// endpoint of the credential issuer should take after getting a
// response from Authlete's `/vci/jwks` API.
type VciJwksResponseAction string

const (
	VciJwksResponseActionOk                  VciJwksResponseAction = "OK"
	VciJwksResponseActionNotFound            VciJwksResponseAction = "NOT_FOUND"
	VciJwksResponseActionInternalServerError VciJwksResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e VciJwksResponseAction) ToPointer() *VciJwksResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VciJwksResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "NOT_FOUND", "INTERNAL_SERVER_ERROR":
			return true
		}
	}
	return false
}

type VciJwksResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the implementation of the JWK Set document
	// endpoint of the credential issuer should take after getting a
	// response from Authlete's `/vci/jwks` API.
	//
	Action *VciJwksResponseAction `json:"action,omitzero"`
	// Get the content that the implementation of the credential issuer
	// metadata endpoint should use when it constructs a response.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (v *VciJwksResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciJwksResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciJwksResponse) GetAction() *VciJwksResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciJwksResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}
