// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VciMetadataResponseAction - The next action that the implementation of the credential issuer
// metadata endpoint (`/.well-known/openid-credential-issuer`)
// should take after getting a response from Authlete's
// `/vci/metadata` API.
type VciMetadataResponseAction string

const (
	VciMetadataResponseActionOk                  VciMetadataResponseAction = "OK"
	VciMetadataResponseActionNotFound            VciMetadataResponseAction = "NOT_FOUND"
	VciMetadataResponseActionInternalServerError VciMetadataResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e VciMetadataResponseAction) ToPointer() *VciMetadataResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VciMetadataResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "NOT_FOUND", "INTERNAL_SERVER_ERROR":
			return true
		}
	}
	return false
}

type VciMetadataResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the implementation of the credential issuer
	// metadata endpoint (`/.well-known/openid-credential-issuer`)
	// should take after getting a response from Authlete's
	// `/vci/metadata` API.
	//
	Action *VciMetadataResponseAction `json:"action,omitzero"`
	// Get the content that the implementation of the credential issuer
	// metadata endpoint should use when it constructs a response.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (v *VciMetadataResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciMetadataResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciMetadataResponse) GetAction() *VciMetadataResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciMetadataResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}
