// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VciOfferInfoRequest struct {
	// The identifier of the credential offer.
	Identifier *string `json:"identifier,omitzero" form:"name=identifier"`
}

func (v *VciOfferInfoRequest) GetIdentifier() *string {
	if v == nil {
		return nil
	}
	return v.Identifier
}
