// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

// VciOfferInfoResponseAction - The result of the `/vci/offer/info` API call.
type VciOfferInfoResponseAction string

const (
	VciOfferInfoResponseActionOk            VciOfferInfoResponseAction = "OK"
	VciOfferInfoResponseActionForbidden     VciOfferInfoResponseAction = "FORBIDDEN"
	VciOfferInfoResponseActionNotFound      VciOfferInfoResponseAction = "NOT_FOUND"
	VciOfferInfoResponseActionCallerError   VciOfferInfoResponseAction = "CALLER_ERROR"
	VciOfferInfoResponseActionAuthleteError VciOfferInfoResponseAction = "AUTHLETE_ERROR"
)

func (e VciOfferInfoResponseAction) ToPointer() *VciOfferInfoResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VciOfferInfoResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "FORBIDDEN", "NOT_FOUND", "CALLER_ERROR", "AUTHLETE_ERROR":
			return true
		}
	}
	return false
}

type VciOfferInfoResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The result of the `/vci/offer/info` API call.
	Action *VciOfferInfoResponseAction `json:"action,omitzero"`
	Info   *CredentialOfferInfo        `json:"info,omitzero"`
}

func (v VciOfferInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciOfferInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciOfferInfoResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciOfferInfoResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciOfferInfoResponse) GetAction() *VciOfferInfoResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciOfferInfoResponse) GetInfo() *CredentialOfferInfo {
	if v == nil {
		return nil
	}
	return v.Info
}
