// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/authlete/authlete-go-sdk/internal/utils"
)

// VciSingleParseResponseAction - The next action that the credential endpoint should take.
type VciSingleParseResponseAction string

const (
	VciSingleParseResponseActionOk                  VciSingleParseResponseAction = "OK"
	VciSingleParseResponseActionBadRequest          VciSingleParseResponseAction = "BAD_REQUEST"
	VciSingleParseResponseActionUnauthorized        VciSingleParseResponseAction = "UNAUTHORIZED"
	VciSingleParseResponseActionForbidden           VciSingleParseResponseAction = "FORBIDDEN"
	VciSingleParseResponseActionInternalServerError VciSingleParseResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e VciSingleParseResponseAction) ToPointer() *VciSingleParseResponseAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VciSingleParseResponseAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "OK", "BAD_REQUEST", "UNAUTHORIZED", "FORBIDDEN", "INTERNAL_SERVER_ERROR":
			return true
		}
	}
	return false
}

type VciSingleParseResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the credential endpoint should take.
	Action *VciSingleParseResponseAction `json:"action,omitzero"`
	// The content of the response to the request sender.
	ResponseContent *string                `json:"responseContent,omitzero"`
	Info            *CredentialRequestInfo `json:"info,omitzero"`
}

func (v VciSingleParseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciSingleParseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciSingleParseResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciSingleParseResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciSingleParseResponse) GetAction() *VciSingleParseResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciSingleParseResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}

func (v *VciSingleParseResponse) GetInfo() *CredentialRequestInfo {
	if v == nil {
		return nil
	}
	return v.Info
}
