// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VerifiedClaimsValidationSchema - The verified claims validation schema set.
type VerifiedClaimsValidationSchema string

const (
	VerifiedClaimsValidationSchemaStandard               VerifiedClaimsValidationSchema = "standard"
	VerifiedClaimsValidationSchemaStandardPlusIDDocument VerifiedClaimsValidationSchema = "standard+id_document"
)

func (e VerifiedClaimsValidationSchema) ToPointer() *VerifiedClaimsValidationSchema {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VerifiedClaimsValidationSchema) IsExact() bool {
	if e != nil {
		switch *e {
		case "standard", "standard+id_document":
			return true
		}
	}
	return false
}
