// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/authlete/authlete-go-sdk/models/components"
)

type ResultError struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string                 `json:"resultMessage,omitzero"`
	HTTPMeta      components.HTTPMetadata `json:"-"`
}

var _ error = &ResultError{}

func (e *ResultError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
