workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Authlete-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/authlete/openapi/refs/heads/main/spec_next.yaml
        overlays:
            - location: /Users/shariq/Documents/Authlete/Prod/Go SDK/.speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/authlete/sdk-workspace/authlete-oas
targets:
    authlete:
        target: go
        source: Authlete-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/authlete/sdk-workspace/authlete-oas-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
